// U28 gauge half: the two encodings of one "additional damage" kit line must generate the SAME
// burst gauge. A `flatDamage` rider has always called `skillGauge` per impact; `extraHitDamagePct`
// did not, so re-encoding a unit between the two primitives silently changed its rotation. As of
// 2026-08-13 both emit (src/engine/sim.ts, firePull). Ruling: docs/data/burst-gauge.md §5 — every
// skill/additional-damage impact generates the caster's flat target per-shot value — measured on
// maiden-ice-rose (slug maiden-ice-rose, RL/Electric — NOT the SG unit `maiden`), whose solo probe
// reads 12.55%/pull in two visible bar sub-steps: 910 weapon (364x2.5) + 364 rider, flat.
//
// WHY THIS TEST BUILDS ITS OWN FIXTURE. All four shipped carriers (modernia, nayuta,
// neon-blue-ocean, neon-vision-eye) hold the rider on a `burstCast` trigger, so its whole live
// window sits inside addGauge's burst-chain + Full-Burst lock and every emission is swallowed —
// which is why the landing moved no comp (censused by
// `npx tsx scripts/battery/u28-gauge-ab.ts --lock-census`: 0 unlocked emissions across 9 comps).
// A test built on a shipped carrier as-shipped would pass identically WITH OR WITHOUT the emission:
// it would pin nothing while looking thorough.
//
// WHY BURSTS ARE DISABLED. Gauge feeds the rotation and the rotation gates gauge, so on a normal
// fight a bigger emission moves the Full-Burst boundaries and every unit's locked/unlocked split
// shifts with them — teammates included. That feedback is real behaviour, but it buries the
// quantity under test in rotation noise (measured: ~6% swings on teammates, and a 0.08% residual
// between arms that is boundary placement, not emission size). `disableBursts` holds the chain at
// stage 0 for the whole fight, so nothing is ever locked or consumed and `gaugeGenerated` becomes a
// pure count of emissions — which makes the comparison EXACT rather than approximate.
//
// Assertions:
//   1. EMISSION LIVE  — an extraHitDamagePct rider generates strictly more gauge than no rider.
//   2. EQUIVALENCE    — it generates EXACTLY the gauge of the flatDamage encoding of the same line.
//                       This is the U28 claim; deleting the skillGauge call fails it by the rider's
//                       whole contribution.
//   3. ONE PER IMPACT — the summed stat is dealt as ONE impact, so TWO extraHitDamagePct riders
//                       still emit once, while two flatDamage riders emit twice. Pins the residual
//                       half of U28 as a known, deliberate asymmetry instead of a future mystery.
import { describe, expect, it } from 'vitest';
import { runComp, withPatchedOverride } from '../lib/harness.js';

// nayuta (slug nayuta, AR/Water) is a shipped extraHitDamagePct carrier, so the fixture stays on a
// real carrier rather than inventing a stat no unit has.
const CARRIER = 'nayuta';
const TEAM = ['liter', 'crown', CARRIER, 'helm'];
const ATK_PCT = 250;

type Encoding =
  'none' | 'extraHit' | 'flatDamage' | 'extraHitx2' | 'flatDamagex2';

/**
 * Total burst gauge generated by the carrier when its rider is encoded as `encoding`.
 *
 * Both encodings are made to fire on EVERY pull, and neither may lead the other: the
 * `extraHitDamagePct` buff is granted once at `battleStart` (durationSec 999) so it is already live
 * when firePull reads the stat on pull 1 — granting it from `shotFired` instead would cost the
 * first pull's emission, since the block fires after that read, and the arms would differ by
 * exactly one impact for a fixture reason rather than an engine one.
 */
function gaugeFor(encoding: Encoding): number {
  const carrier = withPatchedOverride(CARRIER, (ov: any) => {
    // Strip the shipped burstCast rider so the installed one is the only rider in play.
    for (const slot of ['skill1', 'skill2', 'burst']) {
      for (const block of ov[slot] ?? []) {
        block.effects = (block.effects ?? []).filter(
          (e: any) => e.stat !== 'extraHitDamagePct'
        );
      }
    }
    const alwaysOnRider = () => ({
      slot: 'skill1',
      trigger: { kind: 'battleStart' },
      target: { kind: 'self' },
      effects: [
        {
          kind: 'buff',
          stat: 'extraHitDamagePct',
          value: ATK_PCT,
          durationSec: 999,
        },
      ],
    });
    const perPullRider = () => ({
      slot: 'skill1',
      trigger: { kind: 'shotFired' },
      target: { kind: 'enemy' },
      effects: [{ kind: 'flatDamage', atkPct: ATK_PCT }],
    });
    const counts: Record<Encoding, [number, number]> = {
      none: [0, 0],
      extraHit: [1, 0],
      extraHitx2: [2, 0],
      flatDamage: [0, 1],
      flatDamagex2: [0, 2],
    };
    const [extra, flat] = counts[encoding];
    ov.skill1 = [
      ...(ov.skill1 ?? []),
      ...Array.from({ length: extra }, alwaysOnRider),
      ...Array.from({ length: flat }, perPullRider),
    ];
  });
  const res = runComp({
    slugs: TEAM,
    bossElement: 'Water',
    focusSlug: CARRIER,
    overrides: { [CARRIER]: carrier },
    cfg: { disableBursts: true },
  });
  const unit = res.units.find((u) => u.slug === CARRIER);
  if (!unit) {
    throw new Error(`${CARRIER} missing from the result — fixture is stale`);
  }
  return unit.gaugeGenerated;
}

describe('U28: extraHitDamagePct and flatDamage riders generate gauge identically', () => {
  const none = gaugeFor('none');
  const extraHit = gaugeFor('extraHit');
  const flatDamage = gaugeFor('flatDamage');

  it('an extraHitDamagePct rider generates burst gauge at all', () => {
    // Guards the fixture as much as the engine: were these equal, the rider never fired and
    // assertions 2-3 would be vacuously true.
    expect(extraHit).toBeGreaterThan(none);
  });

  it('generates exactly the gauge of the flatDamage encoding of the same line', () => {
    // THE U28 CLAIM. Removing the skillGauge call at the extraHitDamagePct site drops `extraHit`
    // back to `none` and fails this by the rider's entire contribution.
    expect(extraHit).toBeCloseTo(flatDamage, 6);
    expect(extraHit - none).toBeGreaterThan(0);
  });

  it('emits ONCE PER IMPACT, so two summed riders still emit once (residual U28 asymmetry)', () => {
    // extraHitDamagePct is a SUMMED stat dealt as a single impact: doubling the riders doubles the
    // DAMAGE but not the emission count. Two flatDamage riders are two impacts, so they DO emit
    // twice. No shipped unit carries two extraHitDamagePct riders; this pins the difference so a
    // future author meets it as a documented limit rather than a surprise.
    expect(gaugeFor('extraHitx2')).toBeCloseTo(extraHit, 6);
    expect(gaugeFor('flatDamagex2') - flatDamage).toBeCloseTo(
      flatDamage - none,
      6
    );
  });
});
