// Pins the Treasure release-date policy in data/characters.json (owner ruling 2026-08-03): a
// Treasure unit's `releaseDate` is the date its TREASURE released, not the base unit's debut.
//
// WHY A TEST. `releaseDate` is display-only — the unit card's "Released <date>" line — so nothing
// else in the repo would notice it changing. The value is regenerated by `npm run sync` from
// whichever Synergy row bakery-bot's DB matched the unit to, and Synergy carries a Treasure as its
// own row (宝 + the base unit's Japanese name) alongside the base one. Before the ruling that match
// was inconsistent: 18 of the 21 Treasure units read their base debut and 3 read their Treasure
// date. sync.ts now resolves the 宝 row itself, but an upstream re-match could silently undo that,
// and the only symptom would be a wrong date on a card nobody is looking at.
//
// The dates below are NOT hand-authored — they are Synergy's, captured here so the assertion needs
// no network. Re-derive them (and audit the whole column, Treasure or not, against the live source)
// with `npx tsx scripts/audit-release-dates.ts`, which needs DATABASE_PUBLIC_URL.
import { describe, expect, it } from 'vitest';
import data from '../../../data/characters.json' with { type: 'json' };

// slug -> the date that unit's Treasure released, per Synergy's 宝 row (captured 2026-08-03).
const TREASURE_RELEASE_DATES: Record<string, string> = {
  bay: '2025-07-17',
  centi: '2026-02-12',
  diesel: '2024-05-30',
  drake: '2025-01-16',
  exia: '2024-05-30',
  flora: '2026-07-23',
  frima: '2024-05-30',
  helm: '2025-01-16',
  julia: '2025-07-17',
  laplace: '2024-05-30',
  milk: '2025-01-16',
  miranda: '2025-01-16',
  moran: '2026-02-12',
  phantom: '2026-07-23',
  poli: '2025-07-17',
  privaty: '2026-02-12',
  rosanna: '2026-07-23',
  sugar: '2026-07-23',
  tove: '2025-07-17',
  viper: '2024-07-04',
  zwei: '2026-02-12',
};

const characters = data.characters as Record<
  string,
  { releaseDate?: string | null; treasure?: boolean }
>;

describe('Treasure units carry their Treasure release date', () => {
  // Guards the table itself: a NEW Treasure unit must be added above, with its date read off
  // Synergy, rather than quietly skipping the assertion below.
  it('covers every Treasure unit in the roster', () => {
    const treasureSlugs = Object.entries(characters)
      .filter(([, c]) => c.treasure)
      .map(([slug]) => slug)
      .sort();
    expect(treasureSlugs).toEqual(Object.keys(TREASURE_RELEASE_DATES).sort());
  });

  for (const [slug, expected] of Object.entries(TREASURE_RELEASE_DATES)) {
    it(`${slug} released ${expected}`, () => {
      expect(characters[slug]?.releaseDate).toBe(expected);
    });
  }
});

describe('release dates are well-formed', () => {
  it('every date is an ISO calendar date, or null where none is known', () => {
    const malformed = Object.entries(characters)
      .filter(([, c]) => c.releaseDate != null)
      .filter(([, c]) => !/^\d{4}-\d{2}-\d{2}$/.test(c.releaseDate as string))
      .map(([slug]) => slug);
    expect(malformed).toEqual([]);
  });

  // Synergy has no row for anne-miracle-fairy, so there is no date to source. That is the ONLY
  // acceptable reason for a null, and it is worth noticing if the count grows.
  it('exactly one unit has no release date', () => {
    const undated = Object.entries(characters)
      .filter(([, c]) => c.releaseDate == null)
      .map(([slug]) => slug);
    expect(undated).toEqual(['anne-miracle-fairy']);
  });
});
