// Precompute the B1/B2 DPS ranking board into web/public/b1b2dps.json.
//
// Ranks every sim-supported Burst-1/Burst-2 unit by its own DPS in a Solo-style
// no-op control team (see src/ranks/b1b2dps.ts). BUILD OUTPUT — regenerated by
// `npm run ranks:all`, not committed.
//
//   npx tsx scripts/build-b1b2dps.ts [--out <path>]
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import type { DataFile, LevelMultiplier, Element } from '../src/types.js';
import { loadOverride } from '../src/skills/overrides-node.js';
import { unitElements } from '../src/elements.js';
import type { OverrideFile } from '../src/skills/index.js';
import type {
  CubesFile,
  OlLinesFile,
  PrepareDeps,
  SkillLevelData,
} from '../src/prepare.js';
import type { RanksCtx } from '../src/ranks/burstgen.js';
import type { NoopCharacter } from '../src/dpschart/noop.js';
import {
  rankB1B2Dps,
  buildTeam,
  B1B2_DPS_CELLS,
  B1B2_DPS_PROFILES,
  B1B2_DPS_EXTRA_PROFILES,
  type B1B2TestedUnit,
  type B1B2DpsCell,
} from '../src/ranks/b1b2dps.js';
import {
  NOOP_CHARACTERS,
  B1B2_NOOP_CHARACTERS,
} from '../src/dpschart/noop.js';
import type {
  B1B2DpsArtifact,
  B1B2DpsRow,
  RankUnitMeta,
} from '../src/ranks/types.js';

const load = <T>(rel: string): T =>
  JSON.parse(readFileSync(new URL(rel, import.meta.url), 'utf8')) as T;

const data = load<DataFile>('../data/characters.json');
const mult = load<LevelMultiplier>('../data/level-multiplier.json');
const cubes = load<CubesFile>('../data/cubes.json');
const olLines = load<OlLinesFile>('../data/ol-lines.json');
let skillLevels: SkillLevelData = {};
try {
  skillLevels = load<SkillLevelData>('../data/skill-levels.json');
} catch {
  /* optional */
}

const overrides: Record<string, OverrideFile | undefined> = {};
for (const slug of Object.keys(data.characters)) {
  overrides[slug] = loadOverride(slug);
}
// Synthetic controls are not roster entries, but their overrides carry
// framework effects (no-op B1 CDR, no-op B3 mock burst). Load every registered
// synthetic control so a future addition cannot be forgotten.
for (const slug of new Set([
  ...Object.keys(NOOP_CHARACTERS),
  ...Object.keys(B1B2_NOOP_CHARACTERS),
])) {
  overrides[slug] = loadOverride(slug);
}

const deps: PrepareDeps = { overrides, skillLevels, cubes, olLines };
const ctx: RanksCtx = {
  characters: data.characters as Record<string, NoopCharacter>,
  mult,
  deps,
};

// Tested population: every sim-supported B1/B2, plus forced rows for Λ/B3 units
// that the board wants to evaluate at an off-stage slot.
const population: B1B2TestedUnit[] = [];
for (const [slug, c] of Object.entries(data.characters)) {
  if (!c.simSupported) {
    continue;
  }
  if (c.burst === 'I' || c.burst === 'II') {
    population.push({
      slug,
      effectiveBurst: c.burst,
      element: c.element as Element,
      profile: null,
    });
  }
}

// Force Red Hood as B1 and B2, and Rapi: Red Hood as B1. Λ units are pinned via
// lambdaStage; non-Λ units are forced via forceStage.
const FORCED_ROWS: {
  slug: string;
  effectiveBurst: 'I' | 'II';
  forceStage: 1 | 2;
  profile: string;
}[] = [
  { slug: 'red-hood', effectiveBurst: 'I', forceStage: 1, profile: 'as-b1' },
  { slug: 'red-hood', effectiveBurst: 'II', forceStage: 2, profile: 'as-b2' },
  {
    slug: 'rapi-red-hood',
    effectiveBurst: 'I',
    forceStage: 1,
    profile: 'as-b1',
  },
];
for (const f of FORCED_ROWS) {
  const c = data.characters[f.slug];
  if (!c?.simSupported) {
    continue;
  }
  population.push({
    slug: f.slug,
    effectiveBurst: f.effectiveBurst,
    element: c.element as Element,
    profile: f.profile,
    forceStage: f.forceStage,
  });
}

// Add profile rows for units that have canonical partner profiles.
for (const [slug, profileIds] of Object.entries(B1B2_DPS_EXTRA_PROFILES)) {
  const c = data.characters[slug];
  if (!c?.simSupported) {
    continue;
  }
  for (const id of profileIds) {
    const profileDef = B1B2_DPS_PROFILES[id];
    if (!profileDef) {
      continue;
    }
    if (c.burst !== 'I' && c.burst !== 'II') {
      process.stderr.write(
        `b1b2dps: skipping profile ${id} for ${slug} — burst is ${c.burst}, expected I or II\n`
      );
      continue;
    }
    const partner = profileDef.partner;
    const partnerChar =
      B1B2_NOOP_CHARACTERS[partner] ??
      (data.characters[partner] as NoopCharacter | undefined);
    const partnerSupported =
      partner in B1B2_NOOP_CHARACTERS || data.characters[partner]?.simSupported;
    if (!partnerSupported) {
      process.stderr.write(
        `b1b2dps: skipping profile ${id} for ${slug} — partner "${partner}" is not sim-supported\n`
      );
      continue;
    }
    const expectedPartnerBurst = c.burst;
    const actualPartnerBurst = partnerChar?.burst;
    if (actualPartnerBurst !== expectedPartnerBurst) {
      process.stderr.write(
        `b1b2dps: skipping profile ${id} for ${slug} — partner "${partner}" burst is ${actualPartnerBurst}, expected ${expectedPartnerBurst}\n`
      );
      continue;
    }
    const plainUnit: B1B2TestedUnit = {
      slug,
      effectiveBurst: c.burst,
      element: c.element as Element,
      profile: null,
    };
    const profileUnit: B1B2TestedUnit = {
      ...plainUnit,
      profile: id,
    };
    if (
      buildTeam(plainUnit, ctx).team.join(',') ===
      buildTeam(profileUnit, ctx).team.join(',')
    ) {
      process.stderr.write(
        `b1b2dps: skipping profile ${id} for ${slug} — assembled team is identical to the plain row\n`
      );
      continue;
    }
    population.push(profileUnit);
  }
}

const ranked = rankB1B2Dps(population, ctx);

const pack = (
  entries: {
    slug: string;
    dps: number;
    profile: string | null;
    template: 'b1-20s' | 'b1-40s' | 'b2';
  }[]
): B1B2DpsRow[] =>
  entries.map((e): B1B2DpsRow => [
    e.slug,
    Math.round(e.dps),
    e.profile,
    e.template,
  ]);

const cells: B1B2DpsArtifact['cells'] = {
  'c0-neutral': pack(ranked['c0-neutral']),
  'c0-eleadv': pack(ranked['c0-eleadv']),
  'c100-neutral': pack(ranked['c100-neutral']),
  'c100-eleadv': pack(ranked['c100-eleadv']),
};

// Gather unit metadata for every slug that appears in a ranked row.
const rankedSlugs = new Set(population.map((t) => t.slug));
const units: Record<string, RankUnitMeta> = {};
for (const slug of rankedSlugs) {
  const c = data.characters[slug];
  if (!c) {
    continue;
  }
  units[slug] = {
    name: c.name,
    element: c.element as Element,
    elements: unitElements(c),
    weapon: c.weapon,
    burst: c.burst,
    imageUrl: c.imageUrl ?? null,
  };
}

// Profiles map for the frontend's badge tooltip.
const profiles: Record<string, string> = {
  ...Object.fromEntries(
    Object.values(B1B2_DPS_PROFILES).map((p) => [p.id, p.note])
  ),
  'as-b1': 'ranked in the Burst 1 slot',
  'as-b2': 'ranked in the Burst 2 slot',
};

const artifact: B1B2DpsArtifact = {
  generatedAt: new Date().toISOString(),
  methodology:
    'B1/B2 units ranked by their own DPS in a Solo-style no-op control team. ' +
    'Team shape: B1 20s [tested, B2 SR, B2 SR, B3 RL, B3 MG]; B1 40s [tested, B1 AR, B2 SR, B3 RL, B3 MG]; ' +
    'B2 [B1 AR, tested, B2 SR, B3 RL, B3 MG]. The no-op B1 (AR) in the 40s-B1 and B2 templates contributes the standard 7 s team burst CDR via its override; ' +
    "20s-B1 rows have no second B1, so they rely on the tested B1's own CDR. " +
    'For a 20s-B1 profile row with a B1 partner, the team switches to the 40s-B1 template: the partner fills the second B1 slot and the second no-op B2 is removed, ' +
    'so the row gains rotation coverage from the partner at the cost of one B2 slot. Profile rows put the partner first in the stage (e.g. Avistar -> Anis: Star, Chime -> Crown). ' +
    'Each row records its template (20s B1 / 40s B1 / B2); rows are only comparable within the same template group. ' +
    'Investment is scope lock (Base-5, 3★/core 7, no cube/doll). ' +
    'The tested unit is the camera-focused unit (×2.5 burst-gauge generation on charge weapons), matching the Solo framework. ' +
    'Cells: core 0 / core 100 × neutral / elemental advantage (boss weak to the tested unit; for multi-element units the advantage cell uses the native element).',
  units,
  profiles,
  cells,
};

const outArg = process.argv.indexOf('--out');
let out: string;
if (outArg >= 0) {
  const next = process.argv[outArg + 1];
  if (!next) {
    throw new Error('--out requires a path');
  }
  out = next;
} else {
  out = new URL('../web/public/b1b2dps.json', import.meta.url).pathname;
}
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, JSON.stringify(artifact));

const top = (cell: B1B2DpsCell) =>
  ranked[cell]
    .slice(0, 10)
    .map(
      (r) =>
        `  #${r.rank} ${r.slug}${r.profile ? ` [${r.profile}]` : ''} ${r.dps.toFixed(0)}`
    )
    .join('\n');

process.stderr.write(
  `b1b2dps: ${population.length} rows × ${B1B2_DPS_CELLS.length} cells → ${out}\n` +
    B1B2_DPS_CELLS.map((c) => `${c}:\n${top(c)}`).join('\n') +
    '\n'
);
