// Build the archetype tag table the web Team Builder uses to filter NIKKEs by
// what their kit DOES (buffer, reload buffer, distributed damage, …) rather than
// by raw stat (weapon/burst/class/element/manufacturer).
//
// Input (committed, regenerated by `npm run sync`):
//   data/characters.json — only the skill PROSE (skills.skill1/skill2/burst) is
//   parsed. The datamined role.* snapshot is deliberately IGNORED: it contains
//   weapon-table terms like reload_time / penetration / core_damage_rate that
//   would false-positive (e.g. every shotgun "penetration" column is not a kit
//   pierce). Prose is the player-facing kit description = the right source.
//
// Output (committed):
//   data/archetype-tags.json — { vocabulary, tags: { slug: string[] } }.
//
// Regenerate as a full sweep whenever the roster or kit text changes:
//   npx tsx scripts/build-archetype-tags.ts            # dry run: stats only, no write
//   npx tsx scripts/build-archetype-tags.ts --write    # write data/archetype-tags.json
//
// This also runs automatically as the second half of `npm run sync` (chained
// after src/data/sync.ts rewrites characters.json), so a routine sync keeps
// data/archetype-tags.json current with no extra step. The standalone commands
// above are for re-running after a RULE change, or for a dry-run inspection.
//
// The sweep is deterministic and safe to re-run; see docs/data/archetype-tags.md
// for the vocabulary definitions + the manual single-unit workflow (new units are
// tagged one-at-a-time as they land, then the sweep keeps the file sorted/complete).

import { readFileSync, writeFileSync } from 'node:fs';
import type { DataFile } from '../src/types.js';

const OUT = new URL('../data/archetype-tags.json', import.meta.url);
const data: DataFile = JSON.parse(
  readFileSync(new URL('../data/characters.json', import.meta.url), 'utf8'),
);

// ---- prose → blocks -------------------------------------------------------
// A kit reads as a sequence of "■"-prefixed blocks. Each block names its target
// ("Affects all allies" / "Affects self" / "Affects all enemies" / "Affects N
// enemy unit(s)") then lists effect lines using ▲ (buff) / ▼ (debuff) / "Deals".
// Splitting on ■ and reading the target per block is what lets us tell an ally
// ATK ▲ (a buffer) from an enemy ATK ▼ (a debuffer) instead of keyword-matching
// the whole kit blob.
interface Block {
  text: string;
  ally: boolean; // affects at least one ally (incl. "all allies")
  self: boolean; // affects self
  enemy: boolean; // affects at least one enemy
}

function parseBlocks(prose: string): Block[] {
  return prose
    .split('■')
    .map((s) => s.trim())
    .filter(Boolean)
    .map((text) => {
      // Read the target out of the block's "Affects …" clause (the words between
      // "Affects" and the next period/newline), not a fixed literal. Qualified
      // targets — "Affects all Water Code allies", "Affects 2 random ally
      // unit(s)", "Affects all Electric Code enemies" — still carry the ally /
      // enemy keyword in that clause, so matching the clause catches them where
      // a literal like "all allies" would not.
      const ally = /Affects[^.\n]*\ball(?:y|ies)\b/i.test(text);
      const self = /Affects self/i.test(text);
      const enemy =
        /Affects[^.\n]*\benem(?:y|ies)\b/i.test(text) ||
        // "Affects the target(s)" = a single-target enemy hit — unless the same
        // clause is an ally target ("Affects the target Defender ally").
        (/Affects[^.\n]*\btargets?\b/i.test(text) && !ally);
      return { text, ally, self, enemy };
    });
}

const proseOf = (c: DataFile['characters'][string]) =>
  [c.skills?.skill1, c.skills?.skill2, c.skills?.burst]
    .filter(Boolean)
    .join('\n');

// ---- tag vocabulary -------------------------------------------------------
// Controlled, documented set. Each rule = a predicate over the parsed blocks.
// Stat/damage `buffer`-family tags match a buff on self OR allies — a unit that
// only buffs itself (e.g. privaty's self Elemental Advantage buff) still carries
// the tag, because the tag answers "what does this kit buff", not "who does it
// buff for". Burst-support, ally-filter and role tags stay ally-facing (they are
// team roles, not self-buffs). Damage-profile tags (distributed/sustained/
// pierce) key off what the kit deals OR enables. Keep ids kebab-case + ASCII
// (they go into URLs via team-share); the player-facing label carries the ▲.
// `group` buckets the tags for the UI filter panel (see docs/data/archetype-tags.md).
interface TagDef {
  id: string;
  label: string;
  blurb: string;
  group: string;
  test: (blocks: Block[], prose: string) => boolean;
}

// UI filter-panel groups (a starter the owner can rename/rebucket).
const G = {
  stat: 'Stat Buffs',
  dmg: 'Damage Buffs',
  ally: 'Ally Filters',
  burst: 'Burst Support',
  role: 'Role',
} as const;

const allySome = (blocks: Block[], re: RegExp) =>
  blocks.some((b) => b.ally && re.test(b.text));
// Self OR ally (the buffer-family scope): a buff that lands on the unit itself or
// on allies. Never counts enemy-facing blocks.
const buffSome = (blocks: Block[], re: RegExp) =>
  blocks.some((b) => (b.ally || b.self) && re.test(b.text));
// Ally-filter matcher: a block with an "Affects …" clause whose TARGET is the
// qualified ally/allies — the weapon/class keyword modifies the ally target
// ("Affects the target Defender ally", "Affects all shotgun-wielding allies") —
// that does something beneficial for them. Shared by the shotgun / sniper /
// class / … matcher tags. Two guards, both load-bearing:
//  - The keyword must sit in a non-self "Affects …" clause that itself names
//    ally/allies. A class keyword inside an "Affects self …" squad-formation
//    CONDITION is not a target — e.g. delta-ninja-thief's "Affects self if there
//    are no other Defender allies in the squad" lands its shield/taunt/heal on
//    SELF, so it must not tag defender-buffer.
//  - The block must carry a real benefit: a ▲ buff OR a utility effect (heal /
//    shield / invulnerability / cleanse / damage reduction / burst enable). ▲
//    alone is too narrow — biscuit's Defender block is "Affects the target
//    Defender ally. Invincible … Recovers … Max HP" (invulnerability + heal, no
//    ▲), a genuine Defender-ally buff the old ▲-only guard silently dropped.
const ALLY_BENEFIT =
  /▲|shield|Invincib|Indomitab|Invulnerab|(?:Recovers|Restores|Heals?)[^▲\n]*HP|Removes?[^.\n]{0,24}debuff|debuff immunit|(?:Damage|DMG) Taken ▼|shares? damage taken|Equally share|Burst Gauge|Cooldown of[^.\n]{0,20}Burst/i;
const allyFilterClause = (text: string, qualifier: RegExp) =>
  (text.match(/Affects[^.\n]*/gi) ?? []).some(
    (cl) =>
      qualifier.test(cl) &&
      /\ball(?:y|ies)\b/i.test(cl) &&
      !/^Affects self\b/i.test(cl),
  );
const allyQualified = (blocks: Block[], qualifier: RegExp) =>
  blocks.some(
    (blk) =>
      allyFilterClause(blk.text, qualifier) && ALLY_BENEFIT.test(blk.text),
  );

// Generic stat/DMG buffs. Note the datamine writes the generic damage buff as
// "Attack Damage ▲" / "Attack damage ▲" (mixed case), not a bare "Attack ▲", so
// "Attack Damage" must be matched explicitly and case-insensitively.
const STAT_BUFF =
  /(ATK|HP|DEF|Crit Rate|Crit Damage|Critical Rate|Critical Damage|DMG|Attack Damage|Attack) ▲/i;
// Real phrasing is "Elemental Advantage Attack Damage ▲" (the datamine never
// uses a bare "<Element> DMG ▲"); require a ▲ so a passing mention of
// "Elemental Advantage" without a buff does not tag.
const ELEMENT_DMG =
  /Elemental Advantage[^.\n]{0,24}▲|(Fire|Water|Wind|Electric|Iron) DMG ▲|Element DMG ▲/;
// "Pierce" granted on the unit's OWN kit ("Gains Pierce" / "Gain Pierce", always
// a self block) — distinct from "Pierce Damage ▲", which is a damage buff that
// tags pierce-buffer when it lands on allies.
const PIERCE_GRANT =
  /\bGains? (?:continuous )?Pierce\b|\bAdditional Effect: ?Pierce\b|Expands? Pierce range|Piercing Radius/i;
// "Projectile Explosion Damage" dealt as a damage TYPE on one of the kit's OWN
// hits — the datamine writes a projectile's damage line as "Projectile Explosion
// Damage: Deals N% of final ATK as damage" (a typed damage instance). This is the
// DEALER signal, distinct from the "Projectile Explosion Damage ▲" buff, which is
// a damage buff that tags projectile-buffer. Mirrors pierce (dealer) vs
// pierce-buffer: a pure projectile buffer (prika, mint) carries only the ▲ and
// must NOT tag projectile.
const PROJECTILE_DEAL = /Projectile Explosion Damage: Deals/i;

const TAG_DEFS: TagDef[] = [
  // ---- Stat Buffs (▲ to core stats; self or ally) -------------------------
  {
    id: 'buffer',
    label: 'Buffer',
    blurb:
      'Buffs stats (ATK / HP / DEF / Crit / generic DMG up), self or ally.',
    group: G.stat,
    test: (b) => buffSome(b, STAT_BUFF),
  },
  {
    id: 'attack-buffer',
    label: 'ATK ▲',
    blurb: 'Buffs ATK / Attack Damage (self or ally).',
    group: G.stat,
    // "ATK ▲" / "Final ATK ▲" / "Attack Damage ▲" (the datamine's generic damage
    // buff). /ATK ▲/ does not match "Attack Damage ▲" ("Attack" has no "atk"
    // substring), so the generic damage buff needs its own alternative.
    test: (b) => buffSome(b, /(Final ATK|ATK|Attack Damage) ▲/i),
  },
  {
    id: 'def-buffer',
    label: 'DEF ▲',
    blurb: 'Buffs DEF (self or ally).',
    group: G.stat,
    test: (b) => buffSome(b, /DEF ▲/i),
  },
  {
    id: 'hp-buffer',
    label: 'HP ▲',
    blurb: 'Buffs Max HP (self or ally; not cover HP).',
    group: G.stat,
    // "HP ▲" / "Max HP ▲". "Max HP of Cover ▲" does NOT match — "HP" there is
    // followed by " of Cover ▲", not " ▲" — so cover-HP kits stay out.
    test: (b) => buffSome(b, /\bHP ▲/i),
  },
  {
    id: 'reload-buffer',
    label: 'Reload ▲',
    blurb: 'Buffs Reload Speed (self or ally).',
    group: G.stat,
    test: (b) => buffSome(b, /Reload Speed ▲/),
  },
  {
    id: 'charge-buffer',
    label: 'Charge ▲',
    blurb: 'Buffs Charge Speed (self or ally; charge weapons).',
    group: G.stat,
    test: (b) => buffSome(b, /Charge Speed ▲/),
  },
  {
    id: 'charge-damage-buffer',
    label: 'Charge Damage ▲',
    blurb: 'Buffs Charge Damage (self or ally; per charge shot, not speed).',
    group: G.stat,
    // "Charge Damage ▲" / "Charge Damage Multiplier ▲" — distinct from
    // charge-buffer, which keys off "Charge Speed ▲".
    test: (b) => buffSome(b, /Charge Damage[^.\n]{0,16}▲/i),
  },
  {
    id: 'hit-rate-buffer',
    label: 'Hit Rate ▲',
    blurb: 'Buffs Hit Rate / Accuracy (self or ally).',
    group: G.stat,
    test: (b) => buffSome(b, /(Hit Rate|Accuracy) ▲/),
  },
  {
    id: 'ammo-buffer',
    label: 'Ammo ▲',
    blurb: 'Buffs Max Ammunition Capacity (self or ally).',
    group: G.stat,
    test: (b) => buffSome(b, /Max Ammunition Capacity ▲/),
  },
  {
    id: 'incoming-healing-buffer',
    label: 'Incoming Healing ▲',
    blurb: 'Buffs Incoming Healing (self or ally; amplifies heals received).',
    group: G.stat,
    test: (b) => buffSome(b, /Incoming healing ▲/i),
  },
  // ---- Damage Buffs (▲ to damage types; self or ally) ---------------------
  {
    id: 'ele-buffer',
    label: 'Element ▲',
    blurb:
      'Element-focused: buffs Elemental Advantage DMG (self or ally) or keys off a specific element Code.',
    group: G.dmg,
    // Two shapes of element-focused kit, both of which play as element support:
    // (A) buffs Elemental Advantage damage — datamined as "Elemental Advantage
    //     Attack Damage ▲", on allies OR self (a self element-dmg buff still
    //     marks the unit's element role, e.g. anis-sparkling-summer, asuka);
    // (B) an enemy block keyed to a specific element Code — "Affects all Wind
    //     Code enemies … Damage Taken ▲" (brid-silent-track) or "… when
    //     attacking an Electric Code target" (helm-aquamarine, eve).
    test: (b) =>
      buffSome(b, ELEMENT_DMG) ||
      b.some(
        (blk) =>
          blk.enemy &&
          /\b(?:Fire|Water|Wind|Electric|Iron) Code\b/i.test(blk.text),
      ),
  },
  {
    id: 'core-buffer',
    label: 'Core ▲',
    blurb: 'Buffs core hits (Core Hit Rate / Core DMG up, self or ally).',
    group: G.dmg,
    // Real phrasing is "Damage dealt when attacking core ▲" — lowercase "core",
    // so match case-insensitively off the "core … ▲" pair, not a capital "Core".
    test: (b) =>
      buffSome(b, /\bcore\b[^.\n]{0,12}▲|Core (Hit Rate|Damage|Hit DMG) ▲/i),
  },
  {
    id: 'projectile-buffer',
    label: 'Projectile ▲',
    blurb: 'Buffs projectile DMG (self or ally; RL / SR / launcher kits).',
    group: G.dmg,
    // Case-insensitive: SR kits write the buff lowercase as "damage to that
    // projectile ▲" / "damage dealt to that projectile ▲", which a capital-P
    // "Projectile …" match misses. The "damage … projectile ▲" alt catches those
    // without picking up a "Projectile Explosion Radius ▲"-style non-damage buff.
    test: (b) =>
      buffSome(
        b,
        /Projectile[^.\n]{0,24}▲|Projectile (DMG|Damage) ▲|[Dd]amage[^.\n]{0,20}projectile[^.\n]{0,8}▲/i,
      ),
  },
  {
    id: 'pierce-buffer',
    label: 'Pierce ▲',
    blurb: 'Grants/buffs Penetration (pierce), self or ally.',
    group: G.dmg,
    // Ally signal is "Pierce Damage ▲" (or a Penetration ▲ / "grants Pierce").
    test: (b) =>
      buffSome(
        b,
        /(Penetration|Pierce)[^.\n]{0,16}▲|grants?[^.\n]{0,24}\b(?:Penetration|Pierce)\b/i,
      ),
  },
  {
    id: 'true-damage-buffer',
    label: 'True Damage ▲',
    blurb: 'Buffs True Damage (self or ally; ignores DEF).',
    group: G.dmg,
    test: (b) => buffSome(b, /True Damage ▲/i),
  },
  {
    id: 'parts-buffer',
    label: 'Parts ▲',
    blurb: 'Buffs Damage to Parts / Interruption Parts (self or ally).',
    group: G.dmg,
    test: (b) => buffSome(b, /Damage to (?:Interruption )?Parts[^.\n]{0,12}▲/i),
  },
  {
    id: 'sustained-buffer',
    label: 'Sustained ▲',
    blurb: 'Buffs Sustained Damage dealt (self or ally).',
    group: G.dmg,
    test: (b) => buffSome(b, /Sustained Damage[^.\n]{0,12}▲/i),
  },
  {
    id: 'distributed-buffer',
    label: 'Distributed ▲',
    blurb: 'Buffs Distributed Damage dealt (self or ally).',
    group: G.dmg,
    test: (b) => buffSome(b, /Distributed Damage[^.\n]{0,12}▲/i),
  },
  // ---- Ally Filters (buff allies matching a weapon/class filter) ----------
  // The qualifier lives in the block's "Affects …" clause ("Affects all allies
  // with a Shotgun" / "Affects all shotgun-wielding allies" / "Affects all
  // Attacker allies"); allyQualified also requires a ▲ in the same block.
  {
    id: 'shotgun-buffer',
    label: 'Shotgun ▲',
    blurb: 'Buffs shotgun-wielding allies.',
    group: G.ally,
    test: (b) => allyQualified(b, /Affects[^.\n]*shotgun/i),
  },
  {
    id: 'ar-buffer',
    label: 'Assault Rifle ▲',
    blurb: 'Buffs assault-rifle allies.',
    group: G.ally,
    test: (b) => allyQualified(b, /Affects[^.\n]*assault rifle/i),
  },
  {
    id: 'sr-buffer',
    label: 'Sniper Rifle ▲',
    blurb: 'Buffs sniper-rifle allies.',
    group: G.ally,
    test: (b) => allyQualified(b, /Affects[^.\n]*sniper rifle/i),
  },
  {
    id: 'smg-buffer',
    label: 'Submachine Gun ▲',
    blurb: 'Buffs submachine-gun allies.',
    group: G.ally,
    test: (b) => allyQualified(b, /Affects[^.\n]*submachine gun/i),
  },
  {
    id: 'rl-buffer',
    label: 'Rocket Launcher ▲',
    blurb: 'Buffs rocket-launcher allies.',
    group: G.ally,
    test: (b) => allyQualified(b, /Affects[^.\n]*rocket launcher/i),
  },
  {
    id: 'attacker-buffer',
    label: 'Attacker ▲',
    blurb: 'Buffs Attacker-class allies.',
    group: G.ally,
    test: (b) => allyQualified(b, /Affects[^.\n]*\battacker\b/i),
  },
  {
    id: 'defender-buffer',
    label: 'Defender ▲',
    blurb: 'Buffs Defender-class allies.',
    group: G.ally,
    test: (b) => allyQualified(b, /Affects[^.\n]*\bdefender\b/i),
  },
  {
    id: 'supporter-buffer',
    label: 'Supporter ▲',
    blurb: 'Buffs Supporter-class allies.',
    group: G.ally,
    test: (b) => allyQualified(b, /Affects[^.\n]*\bsupporter\b/i),
  },
  // ---- Burst Support (ally-facing team burst enablement) ------------------
  {
    id: 'burst-gauge-buffer',
    label: 'Burst Gauge ▲',
    blurb: 'Fills ally Burst Gauge / buffs Burst Gauge filling speed.',
    group: G.burst,
    // Two phrasings: "Burst Gauge filling speed ▲" and "Fills Burst Gauge by …".
    test: (b) =>
      allySome(b, /Burst Gauge[^.\n]{0,24}▲|Fills?[^.\n]{0,16}Burst Gauge/i),
  },
  {
    id: 'burst-cdr',
    label: 'Burst CDR',
    blurb: 'Reduces ally Burst Skill cooldown.',
    group: G.burst,
    test: (b) => allySome(b, /Cooldown of[^.\n]{0,20}Burst[^.\n]{0,12}▼/i),
  },
  {
    id: 'burst-stage',
    label: 'Burst Stage',
    blurb: 'Re-enters / advances the Burst Stage for allies.',
    group: G.burst,
    test: (b) => allySome(b, /Re-?enters? Burst/i),
  },
  // ---- Role (utility + damage profile) ------------------------------------
  {
    id: 'healer',
    label: 'Healer',
    blurb: 'Recovers ally HP.',
    group: G.role,
    // Heal amounts are datamined with decimals ("Recovers 4.86% of … Max HP"),
    // so a plain [^.\n] stop — meant to block sentence periods — dies on the
    // decimal point and never reaches "HP". Allow a period only when a digit
    // follows (a decimal); that still blocks crossing a sentence boundary.
    test: (b) =>
      b.some(
        (blk) =>
          blk.ally &&
          /(Recovers|Restores|Heal)(?:[^.\n]|\.(?=\d)){0,60}HP/i.test(blk.text),
      ),
  },
  {
    id: 'shield',
    label: 'Shield',
    blurb: 'Grants allies a shield.',
    group: G.role,
    test: (b) => b.some((blk) => blk.ally && /shield/i.test(blk.text)),
  },
  {
    id: 'taunt',
    label: 'Taunt',
    blurb: 'Provoke / draw enemy fire (tank).',
    group: G.role,
    // The datamine keyword is "Taunt"/"Taunts" (usually prefixed "Attract:");
    // "Provoke" never appears in kit prose.
    test: (_b, p) => /\bTaunt|\bAttract\b|\bProvokes?\b/i.test(p),
  },
  {
    id: 'debuffer',
    label: 'Debuffer',
    blurb: 'Lowers enemy DEF/ATK or raises damage taken.',
    group: G.role,
    test: (b) =>
      b.some(
        (blk) =>
          blk.enemy &&
          /(DEF ▼|ATK ▼|(Received|Damage Taken|DMG Taken)[^.\n]{0,16}▲|takes? .*additional damage)/i.test(
            blk.text,
          ),
      ),
  },
  {
    id: 'damage-reduction',
    label: 'Damage Reduction',
    blurb: 'Lowers Damage Taken by allies.',
    group: G.role,
    test: (b) => allySome(b, /(Damage|DMG) Taken ▼/i),
  },
  {
    id: 'damage-share',
    label: 'Damage Share',
    blurb: 'Shares damage taken across allies (tank).',
    group: G.role,
    test: (b) => allySome(b, /shares? damage taken|Equally share/i),
  },
  {
    id: 'invulnerability',
    label: 'Invulnerability',
    blurb: 'Grants allies invulnerability / indomitability.',
    group: G.role,
    test: (b) => allySome(b, /Invincib|Indomitab|Invulnerab/i),
  },
  {
    id: 'cleanse',
    label: 'Cleanse',
    blurb: 'Removes ally debuffs / grants debuff immunity.',
    group: G.role,
    test: (b) =>
      allySome(
        b,
        /Removes? \d+ debuff|debuff immunit|Removes?[^.\n]{0,24}debuff/i,
      ),
  },
  {
    id: 'sustained-damage',
    label: 'Sustained Damage',
    blurb: 'Deals or enables sustained single-target damage.',
    group: G.role,
    test: (_b, p) => /sustained damage/i.test(p),
  },
  {
    id: 'distributed-damage',
    label: 'Distributed Damage',
    blurb: 'Deals or enables distributed damage (split across the wave).',
    group: G.role,
    test: (_b, p) => /distributed damage/i.test(p),
  },
  {
    id: 'pierce',
    label: 'Pierce',
    blurb: 'Own attacks penetrate (ignore DEF / shield-pierce).',
    group: G.role,
    // Pierce is a property the kit grants ITSELF ("Gains Pierce" / "Gain Pierce",
    // a self block) — not an enemy-affecting block. "Pierce Damage ▲" is a damage
    // buff and is handled by pierce-buffer, not here.
    test: (b) => b.some((blk) => PIERCE_GRANT.test(blk.text)),
  },
  {
    id: 'projectile',
    label: 'Projectile',
    blurb: 'Deals projectile explosion damage (RL / SR projectile kits).',
    group: G.role,
    // Projectile explosion damage dealt as a damage TYPE on the kit's own hit
    // ("Projectile Explosion Damage: Deals N% of final ATK as damage") — the
    // dealer signal. Distinct from the "Projectile Explosion Damage ▲" buff, which
    // tags projectile-buffer (mirrors pierce dealer vs pierce-buffer).
    test: (b) => b.some((blk) => PROJECTILE_DEAL.test(blk.text)),
  },
];

// ---- run ------------------------------------------------------------------
const tagsBySlug: Record<string, string[]> = {};
for (const [slug, c] of Object.entries(data.characters)) {
  const prose = proseOf(c);
  const blocks = parseBlocks(prose);
  const hits = TAG_DEFS.filter((t) => t.test(blocks, prose)).map((t) => t.id);
  if (hits.length) tagsBySlug[slug] = hits;
}

// stats (always printed) — validate the rules against the real roster before --write.
const counts = new Map<string, number>();
for (const ids of Object.values(tagsBySlug))
  for (const id of ids) counts.set(id, (counts.get(id) ?? 0) + 1);
const total = Object.keys(data.characters).length;
const tagged = Object.keys(tagsBySlug).length;
console.log(`archetype tags — ${tagged}/${total} characters tagged\n`);
for (const def of TAG_DEFS) {
  const n = counts.get(def.id) ?? 0;
  const examples = Object.entries(tagsBySlug)
    .filter(([, ids]) => ids.includes(def.id))
    .slice(0, 6)
    .map(([slug]) => slug);
  console.log(`${String(n).padStart(4)}  ${def.id.padEnd(20)} ${def.label}`);
  if (examples.length) console.log(`        e.g. ${examples.join(', ')}`);
}
const untagged = Object.keys(data.characters).filter((s) => !tagsBySlug[s]);
console.log(`\n${untagged.length} untagged:`);
console.log(`  ${untagged.join(', ') || '(none)'}`);

if (!process.argv.includes('--write')) {
  console.log('\n(dry run — pass --write to emit data/archetype-tags.json)');
  process.exit(0);
}

// ---- write ----------------------------------------------------------------
const vocabulary: Record<
  string,
  { label: string; blurb: string; group: string }
> = {};
for (const def of TAG_DEFS)
  vocabulary[def.id] = { label: def.label, blurb: def.blurb, group: def.group };

// sort slugs + each tag list for a stable, diff-friendly file.
const tags: Record<string, string[]> = {};
for (const slug of Object.keys(tagsBySlug).sort()) {
  tags[slug] = [...tagsBySlug[slug]].sort(
    (a, b) =>
      TAG_DEFS.findIndex((d) => d.id === a) -
      TAG_DEFS.findIndex((d) => d.id === b),
  );
}

const out = {
  updated: new Date().toISOString().slice(0, 10),
  generated: 'scripts/build-archetype-tags.ts',
  source:
    'data/characters.json — skill prose only (skills.skill1/skill2/burst); role.* datamine ignored',
  policy:
    'Archetype tags for Team Builder filtering. Derived deterministically from kit prose by ' +
    'scripts/build-archetype-tags.ts (re-run as a sweep with --write). The prose is split on the ' +
    '"■" block marker and each block\'s "Affects …" target is read, so an ally ATK ▲ tags `buffer` ' +
    'while an enemy ATK ▼ tags `debuffer`. Stat/damage buffer-family tags match a buff on self OR ' +
    'allies (a self-only buffer still carries the tag); burst-support, ally-filter and role tags stay ' +
    'ally-facing. Each tag carries a `group` for the UI filter panel. ' +
    'Manual edits are allowed for edge cases but will be overwritten by the next --write sweep; ' +
    'to make a change stick, adjust the rule in build-archetype-tags.ts. See docs/data/archetype-tags.md.',
  vocabulary,
  tags,
};

writeFileSync(OUT, JSON.stringify(out, null, 1));
console.log(
  `\nwrote ${OUT.pathname} (${Object.keys(tags).length} slugs, ${TAG_DEFS.length} tags)`,
);
