// Validate override files:
//   npx tsx scripts/validate-overrides.ts <slug> [slug...]
// 1. structural check against the effect schema — the PURE rules live in
//    src/skills/validate-structural.ts (importable + unit-tested; extracted 2026-08-10 so a test
//    never has to touch src/skills/overrides/ to exercise them)
// 2. resolveSkills with the override — reports remaining warnings
// 3. smoke sim: unit in a standard team; flags crashes, zero damage, absurd shares
import { readFileSync } from 'node:fs';
import { squadOf } from '../src/data/squads.js';
import { runSim } from '../src/engine/sim.js';
import { resolveSkills } from '../src/skills/index.js';
import { loadOverride } from '../src/skills/overrides-node.js';
import { structuralCheck } from '../src/skills/validate-structural.js';
import type { DataFile, LevelMultiplier, SimConfig } from '../src/types.js';

const data: DataFile = JSON.parse(
  readFileSync(new URL('../data/characters.json', import.meta.url), 'utf8')
);
const mult: LevelMultiplier = JSON.parse(
  readFileSync(
    new URL('../data/level-multiplier.json', import.meta.url),
    'utf8'
  )
);

// Per-unit blablalink level arrays, so the structural pass can resolve every `levelScale`
// anchor. Optional on disk (regenerated by src/data/sync-skill-levels.ts).
let skillLevels: Record<
  string,
  { skill1: number[][]; skill2: number[][]; burst: number[][] }
> = {};
try {
  skillLevels = JSON.parse(
    readFileSync(new URL('../data/skill-levels.json', import.meta.url), 'utf8')
  );
} catch {
  /* optional */
}

const CTX = {
  characterSlugs: new Set(Object.keys(data.characters)),
  squadOf,
};

function validate(slug: string): boolean {
  const c: any = data.characters[slug];
  if (!c) {
    console.log(
      `- ${slug}: not in roster (Bossing C-or-below prune) — override kept on disk, skipped`
    );
    return true;
  }
  const override = loadOverride(slug);
  if (!override) {
    console.log(`✗ ${slug}: no override file`);
    return false;
  }

  // Structural pass. `warnings` are non-fatal authoring notes: the line IS valid JSON and the
  // engine accepts the file, but the effect will not reach the damage model (documented engine
  // gaps, rot-prone citations) — failing them would turn verify.sh red on correct data.
  const { errors, warnings: authoringWarnings } = structuralCheck(
    slug,
    override,
    { ...CTX, levelArrays: skillLevels[slug] }
  );

  if (errors.length) {
    console.log(`✗ ${slug}: structural errors`);
    errors.forEach((e) => console.log(`   - ${e}`));
    return false;
  }

  const resolved = resolveSkills(c, override);
  // smoke sim: put the unit in a standard comp by burst type
  const teamsByBurst: Record<string, string[]> = {
    I: [slug, 'crown', 'naga', 'modernia', 'alice'],
    II: ['liter', slug, 'naga', 'modernia', 'alice'],
    III: ['liter', 'crown', 'naga', slug, 'alice'],
    Λ: [slug, 'crown', 'naga', 'modernia', 'alice'],
  };
  const slugs = teamsByBurst[c.burst] ?? teamsByBurst.III;
  const chars = slugs.map((s) => data.characters[s] as any);
  const cfg: SimConfig = {
    slugs,
    bossElement: null,
    bossDef: 140,
    level: 400,
    copies: 3,
    doll: false,
    ol: 'base5',
    coreHitRate: 0,
    rangeBonus: true,
    durationSec: 180,
  };
  const prepared = chars.map((ch) => ({
    skills: resolveSkills(ch, loadOverride(ch.slug)),
    extraStats: [],
    loadout: [],
  }));
  try {
    const r = runSim(chars, mult, cfg, prepared);
    const u = r.units[slugs.indexOf(slug)];
    const flags: string[] = [];
    if (u.totalDamage <= 0 && c.class === 'Attacker') {
      flags.push('zero damage for an Attacker');
    }
    if (u.share > 0.9) {
      flags.push(`suspicious ${(u.share * 100).toFixed(0)}% team share`);
    }
    console.log(
      `✓ ${slug}: valid | dmg ${(u.totalDamage / 1e6).toFixed(1)}M (${(u.share * 100).toFixed(1)}%) bursts ${u.burstCasts} | remaining warnings: ${resolved.warnings.length + authoringWarnings.length}${flags.length ? ' | FLAGS: ' + flags.join('; ') : ''}`
    );
    resolved.warnings.forEach((w) => console.log(`   ! ${w}`));
    authoringWarnings.forEach((w) => console.log(`   ! ${w}`));
    return flags.length === 0;
  } catch (e) {
    console.log(`✗ ${slug}: sim crashed — ${(e as Error).message}`);
    return false;
  }
}

const slugs = process.argv.slice(2);
if (!slugs.length) {
  console.error(
    'usage: npx tsx scripts/validate-overrides.ts <slug> [slug...]'
  );
  process.exit(1);
}
let ok = true;
for (const s of slugs) {
  ok = validate(s) && ok;
}
process.exit(ok ? 0 : 1);
