// GENERATED by scripts/build-meta-weights.ts — do not edit by hand.
// Meta-popularity weights for the web team/roster generators (enikk top-100
// audit, per boss-weakness element; prydwen bossing-tier fallback for new units).
export interface MetaWeightEntry {
  raid: string;
  boss: string;
  /** slug → enikk popularity 0..1 for this boss-weakness raid */
  unitPop: Record<string, number>;
  /** modeled-complete popular comps (slugs) with normalized ranker count 0..1 */
  comps: { slugs: string[]; pop: number }[];
}
export interface MetaWeightsFile {
  generated: string;
  source: string;
  /** strong co-equal blend weight W: score = dmg × (1 + W·prior) */
  weightDefault: number;
  /** exact-comp match contribution to the prior */
  comboWeight: number;
  /** keyed by the element the boss is weak to (the UI weakness pick) */
  byWeakness: Record<string, MetaWeightEntry>;
  /** element-agnostic tier score for units absent from all audited raids */
  tierPop: Record<string, number>;
  fallbackSlugs: string[];
}

export const META_WEIGHTS: MetaWeightsFile = {
 "generated": "scripts/build-meta-weights.ts",
 "source": "docs/enikk-top100-audit.md + data/bossing-tiers.json",
 "weightDefault": 1,
 "comboWeight": 0.6,
 "byWeakness": {
  "Water": {
   "raid": "Fire",
   "boss": "Fire",
   "unitPop": {
    "tove": 1,
    "dorothy-serendipity": 1,
    "arcana-fortune-mate": 1,
    "drake": 1,
    "soline-frost-ticket": 1,
    "anis-star": 1,
    "bready": 0.96,
    "anchor-innocent-maid": 0.99,
    "diesel-winter-sweets": 0.83,
    "mast-romantic-maid": 1,
    "crown": 1,
    "liter": 0.9,
    "helm": 1,
    "ludmilla-winter-owner": 1,
    "elegg-boom-and-shock": 0.99,
    "nayuta": 1,
    "mint": 1,
    "quency-escape-queen": 0.85,
    "rapi-red-hood": 1,
    "red-hood": 0.93,
    "prika": 0.65,
    "zwei": 0.71,
    "snow-white-heavy-arms": 1,
    "privaty": 1,
    "little-mermaid": 1,
    "miranda": 0.29,
    "alice": 0.31,
    "velvet": 0.12,
    "guillotine-winter-slayer": 0.15,
    "mihara-bonding-chain": 0.05,
    "moran": 0.1,
    "neon-vision-eye": 0.07,
    "naga": 0.03,
    "rosanna-chic-ocean": 0.01,
    "liberalio": 0.02,
    "scarlet-black-shadow": 0.01,
    "ada": 0.01,
    "cinderella": 0.01
   },
   "comps": [
    {
     "slugs": [
      "mint",
      "quency-escape-queen",
      "rapi-red-hood",
      "red-hood",
      "prika"
     ],
     "pop": 1
    },
    {
     "slugs": [
      "miranda",
      "crown",
      "snow-white-heavy-arms",
      "privaty",
      "little-mermaid"
     ],
     "pop": 0.5455
    },
    {
     "slugs": [
      "rapi-red-hood",
      "mint",
      "alice",
      "red-hood",
      "prika"
     ],
     "pop": 0.3409
    },
    {
     "slugs": [
      "rapi-red-hood",
      "nayuta",
      "red-hood",
      "quency-escape-queen",
      "velvet"
     ],
     "pop": 0.2727
    },
    {
     "slugs": [
      "rapi-red-hood",
      "nayuta",
      "quency-escape-queen",
      "guillotine-winter-slayer",
      "red-hood"
     ],
     "pop": 0.1818
    },
    {
     "slugs": [
      "miranda",
      "nayuta",
      "snow-white-heavy-arms",
      "privaty",
      "little-mermaid"
     ],
     "pop": 0.1136
    },
    {
     "slugs": [
      "rapi-red-hood",
      "nayuta",
      "red-hood",
      "quency-escape-queen",
      "mihara-bonding-chain"
     ],
     "pop": 0.1136
    },
    {
     "slugs": [
      "rapi-red-hood",
      "nayuta",
      "quency-escape-queen",
      "diesel-winter-sweets",
      "red-hood"
     ],
     "pop": 0.0909
    },
    {
     "slugs": [
      "moran",
      "nayuta",
      "helm",
      "ludmilla-winter-owner",
      "elegg-boom-and-shock"
     ],
     "pop": 0.0909
    },
    {
     "slugs": [
      "ludmilla-winter-owner",
      "helm",
      "elegg-boom-and-shock",
      "crown",
      "moran"
     ],
     "pop": 0.0909
    },
    {
     "slugs": [
      "rapi-red-hood",
      "mint",
      "alice",
      "quency-escape-queen",
      "prika"
     ],
     "pop": 0.0455
    },
    {
     "slugs": [
      "anis-star",
      "neon-vision-eye",
      "alice",
      "mint",
      "prika"
     ],
     "pop": 0.0455
    },
    {
     "slugs": [
      "rapi-red-hood",
      "nayuta",
      "alice",
      "red-hood",
      "quency-escape-queen"
     ],
     "pop": 0.0227
    },
    {
     "slugs": [
      "rapi-red-hood",
      "crown",
      "red-hood",
      "quency-escape-queen",
      "naga"
     ],
     "pop": 0.0227
    },
    {
     "slugs": [
      "anis-star",
      "nayuta",
      "privaty",
      "ludmilla-winter-owner",
      "elegg-boom-and-shock"
     ],
     "pop": 0.0227
    },
    {
     "slugs": [
      "crown",
      "moran",
      "helm",
      "alice",
      "mast-romantic-maid"
     ],
     "pop": 0.0227
    },
    {
     "slugs": [
      "rapi-red-hood",
      "crown",
      "alice",
      "quency-escape-queen",
      "naga"
     ],
     "pop": 0.0227
    },
    {
     "slugs": [
      "rapi-red-hood",
      "mint",
      "alice",
      "prika",
      "neon-vision-eye"
     ],
     "pop": 0.0227
    },
    {
     "slugs": [
      "moran",
      "nayuta",
      "helm",
      "guillotine-winter-slayer",
      "ludmilla-winter-owner"
     ],
     "pop": 0.0227
    },
    {
     "slugs": [
      "crown",
      "privaty",
      "alice",
      "rapi-red-hood",
      "naga"
     ],
     "pop": 0.0227
    },
    {
     "slugs": [
      "mint",
      "rapi-red-hood",
      "cinderella",
      "red-hood",
      "prika"
     ],
     "pop": 0.0227
    }
   ]
  },
  "Electric": {
   "raid": "Water",
   "boss": "Water",
   "unitPop": {
    "isabel": 1,
    "anis-star": 1,
    "cinderella": 1,
    "arcana": 1,
    "crown": 1,
    "miranda": 0.99,
    "takina": 0.93,
    "ada": 0.99,
    "rouge": 0.85,
    "ein": 0.99,
    "maiden-ice-rose": 1,
    "ade-agent-bunny": 0.85,
    "moran": 1,
    "anis-sparkling-summer": 1,
    "privaty": 1,
    "little-mermaid": 1,
    "mast-romantic-maid": 0.94,
    "neon-vision-eye": 1,
    "liberalio": 1,
    "anchor-innocent-maid": 0.76,
    "rapi-red-hood": 0.95,
    "nayuta": 0.98,
    "snow-white-heavy-arms": 0.97,
    "jill": 0.42,
    "mihara-bonding-chain": 0.54,
    "liter": 0.19,
    "trina": 0.33,
    "scarlet": 0.53,
    "velvet": 0.12,
    "diesel-winter-sweets": 0.14,
    "mari": 0.13,
    "helm": 0.2,
    "ludmilla-winter-owner": 0.07,
    "volume": 0.01,
    "zwei": 0.03,
    "d-killer-wife": 0.01,
    "soline-frost-ticket": 0.02,
    "grave": 0.03,
    "snow-white": 0.01
   },
   "comps": [
    {
     "slugs": [
      "miranda",
      "takina",
      "ada",
      "rouge",
      "ein"
     ],
     "pop": 1
    },
    {
     "slugs": [
      "rapi-red-hood",
      "nayuta",
      "snow-white-heavy-arms",
      "jill",
      "mihara-bonding-chain"
     ],
     "pop": 0.4265
    },
    {
     "slugs": [
      "miranda",
      "takina",
      "ein",
      "ada",
      "little-mermaid"
     ],
     "pop": 0.3676
    },
    {
     "slugs": [
      "nayuta",
      "little-mermaid",
      "neon-vision-eye",
      "liberalio",
      "velvet"
     ],
     "pop": 0.1765
    },
    {
     "slugs": [
      "neon-vision-eye",
      "crown",
      "moran",
      "liberalio",
      "mast-romantic-maid"
     ],
     "pop": 0.1471
    },
    {
     "slugs": [
      "rapi-red-hood",
      "nayuta",
      "jill",
      "snow-white-heavy-arms",
      "ludmilla-winter-owner"
     ],
     "pop": 0.0441
    },
    {
     "slugs": [
      "diesel-winter-sweets",
      "nayuta",
      "snow-white-heavy-arms",
      "rouge",
      "mihara-bonding-chain"
     ],
     "pop": 0.0441
    },
    {
     "slugs": [
      "rapi-red-hood",
      "jill",
      "nayuta",
      "snow-white-heavy-arms",
      "privaty"
     ],
     "pop": 0.0294
    },
    {
     "slugs": [
      "little-mermaid",
      "nayuta",
      "neon-vision-eye",
      "mast-romantic-maid",
      "liberalio"
     ],
     "pop": 0.0294
    },
    {
     "slugs": [
      "miranda",
      "ade-agent-bunny",
      "ein",
      "rouge",
      "ada"
     ],
     "pop": 0.0294
    },
    {
     "slugs": [
      "rapi-red-hood",
      "nayuta",
      "snow-white-heavy-arms",
      "ein",
      "ludmilla-winter-owner"
     ],
     "pop": 0.0147
    },
    {
     "slugs": [
      "miranda",
      "grave",
      "ada",
      "mihara-bonding-chain",
      "little-mermaid"
     ],
     "pop": 0.0147
    },
    {
     "slugs": [
      "miranda",
      "grave",
      "ein",
      "rouge",
      "ada"
     ],
     "pop": 0.0147
    },
    {
     "slugs": [
      "rapi-red-hood",
      "nayuta",
      "ein",
      "diesel-winter-sweets",
      "mihara-bonding-chain"
     ],
     "pop": 0.0147
    },
    {
     "slugs": [
      "miranda",
      "ade-agent-bunny",
      "snow-white-heavy-arms",
      "little-mermaid",
      "ada"
     ],
     "pop": 0.0147
    }
   ]
  },
  "Fire": {
   "raid": "Wind",
   "boss": "Wind",
   "unitPop": {
    "tove": 1,
    "arcana-fortune-mate": 1,
    "dorothy-serendipity": 1,
    "drake": 1,
    "soline-frost-ticket": 1,
    "miranda": 1,
    "nayuta": 1,
    "ada": 0.98,
    "rouge": 0.78,
    "mihara-bonding-chain": 1,
    "liter": 1,
    "grave": 1,
    "alice": 0.95,
    "modernia": 0.94,
    "brid-silent-track": 1,
    "moran": 1,
    "snow-white-heavy-arms": 0.84,
    "mast-romantic-maid": 1,
    "diesel-winter-sweets": 1,
    "crown": 1,
    "little-mermaid": 1,
    "helm": 0.99,
    "privaty": 1,
    "rapi-red-hood": 1,
    "d-killer-wife": 0.22,
    "maxwell": 0.16,
    "isabel": 0.06,
    "arcana": 0.06,
    "asuka-wille": 0.02,
    "asuka": 0.02,
    "cinderella": 0.03,
    "zwei": 0.01,
    "ludmilla-winter-owner": 0.01,
    "liberalio": 0.01
   },
   "comps": [
    {
     "slugs": [
      "miranda",
      "nayuta",
      "ada",
      "rouge",
      "mihara-bonding-chain"
     ],
     "pop": 1
    },
    {
     "slugs": [
      "crown",
      "little-mermaid",
      "helm",
      "privaty",
      "rapi-red-hood"
     ],
     "pop": 0.5974
    },
    {
     "slugs": [
      "crown",
      "mast-romantic-maid",
      "little-mermaid",
      "rapi-red-hood",
      "helm"
     ],
     "pop": 0.5844
    },
    {
     "slugs": [
      "miranda",
      "nayuta",
      "ada",
      "d-killer-wife",
      "mihara-bonding-chain"
     ],
     "pop": 0.2468
    },
    {
     "slugs": [
      "crown",
      "little-mermaid",
      "rapi-red-hood",
      "helm",
      "modernia"
     ],
     "pop": 0.039
    },
    {
     "slugs": [
      "nayuta",
      "miranda",
      "ada",
      "little-mermaid",
      "mihara-bonding-chain"
     ],
     "pop": 0.026
    },
    {
     "slugs": [
      "crown",
      "asuka-wille",
      "little-mermaid",
      "rapi-red-hood",
      "privaty"
     ],
     "pop": 0.026
    },
    {
     "slugs": [
      "miranda",
      "maxwell",
      "mihara-bonding-chain",
      "rouge",
      "nayuta"
     ],
     "pop": 0.013
    },
    {
     "slugs": [
      "helm",
      "nayuta",
      "miranda",
      "d-killer-wife",
      "mihara-bonding-chain"
     ],
     "pop": 0.013
    },
    {
     "slugs": [
      "little-mermaid",
      "crown",
      "privaty",
      "rapi-red-hood",
      "alice"
     ],
     "pop": 0.013
    },
    {
     "slugs": [
      "crown",
      "little-mermaid",
      "helm",
      "ludmilla-winter-owner",
      "rapi-red-hood"
     ],
     "pop": 0.013
    }
   ]
  },
  "Iron": {
   "raid": "Electric",
   "boss": "Electric",
   "unitPop": {
    "crown": 1,
    "rapi-red-hood": 1,
    "little-mermaid": 1,
    "eve": 1,
    "mast-romantic-maid": 1,
    "tove": 0.98,
    "nayuta": 1,
    "soda-twinkling-bunny": 0.98,
    "dorothy-serendipity": 0.97,
    "drake": 0.98,
    "miranda": 0.99,
    "ade-agent-bunny": 0.97,
    "snow-white": 0.94,
    "ada": 0.88,
    "helm-aquamarine": 1,
    "maxwell": 0.4,
    "liter": 1,
    "takina": 0.94,
    "chisato": 0.94,
    "helm": 0.61,
    "raven": 1,
    "moran": 0.78,
    "privaty": 0.94,
    "snow-white-heavy-arms": 0.7,
    "rosanna-chic-ocean": 0.25,
    "milk-blooming-bunny": 0.55,
    "laplace": 0.13,
    "grave": 0.73,
    "red-hood": 0.57,
    "diesel-winter-sweets": 0.12,
    "zwei": 0.13,
    "rouge": 0.21,
    "mihara-bonding-chain": 0.1,
    "liberalio": 0.03,
    "leona": 0.02,
    "cinderella": 0.07,
    "d-killer-wife": 0.03,
    "anchor-innocent-maid": 0.02,
    "blanc": 0.01,
    "arcana": 0.01,
    "isabel": 0.01
   },
   "comps": [
    {
     "slugs": [
      "crown",
      "rapi-red-hood",
      "little-mermaid",
      "eve",
      "mast-romantic-maid"
     ],
     "pop": 1
    },
    {
     "slugs": [
      "tove",
      "nayuta",
      "soda-twinkling-bunny",
      "dorothy-serendipity",
      "drake"
     ],
     "pop": 0.9149
    },
    {
     "slugs": [
      "moran",
      "takina",
      "chisato",
      "ada",
      "privaty"
     ],
     "pop": 0.1383
    },
    {
     "slugs": [
      "moran",
      "snow-white-heavy-arms",
      "takina",
      "chisato",
      "privaty"
     ],
     "pop": 0.0957
    },
    {
     "slugs": [
      "moran",
      "grave",
      "red-hood",
      "milk-blooming-bunny",
      "privaty"
     ],
     "pop": 0.0745
    },
    {
     "slugs": [
      "tove",
      "grave",
      "soda-twinkling-bunny",
      "dorothy-serendipity",
      "drake"
     ],
     "pop": 0.0745
    },
    {
     "slugs": [
      "grave",
      "moran",
      "milk-blooming-bunny",
      "snow-white-heavy-arms",
      "privaty"
     ],
     "pop": 0.0745
    },
    {
     "slugs": [
      "moran",
      "grave",
      "milk-blooming-bunny",
      "raven",
      "privaty"
     ],
     "pop": 0.0426
    },
    {
     "slugs": [
      "moran",
      "chisato",
      "diesel-winter-sweets",
      "takina",
      "red-hood"
     ],
     "pop": 0.0426
    },
    {
     "slugs": [
      "moran",
      "grave",
      "snow-white-heavy-arms",
      "red-hood",
      "privaty"
     ],
     "pop": 0.0426
    },
    {
     "slugs": [
      "privaty",
      "grave",
      "milk-blooming-bunny",
      "rouge",
      "red-hood"
     ],
     "pop": 0.0319
    },
    {
     "slugs": [
      "crown",
      "rapi-red-hood",
      "little-mermaid",
      "privaty",
      "eve"
     ],
     "pop": 0.0319
    },
    {
     "slugs": [
      "takina",
      "rouge",
      "chisato",
      "diesel-winter-sweets",
      "red-hood"
     ],
     "pop": 0.0319
    },
    {
     "slugs": [
      "moran",
      "chisato",
      "takina",
      "diesel-winter-sweets",
      "mihara-bonding-chain"
     ],
     "pop": 0.0319
    },
    {
     "slugs": [
      "moran",
      "grave",
      "milk-blooming-bunny",
      "red-hood",
      "mihara-bonding-chain"
     ],
     "pop": 0.0319
    },
    {
     "slugs": [
      "crown",
      "raven",
      "little-mermaid",
      "rapi-red-hood",
      "privaty"
     ],
     "pop": 0.0213
    },
    {
     "slugs": [
      "miranda",
      "ada",
      "takina",
      "rouge",
      "chisato"
     ],
     "pop": 0.0213
    },
    {
     "slugs": [
      "chisato",
      "rouge",
      "cinderella",
      "takina",
      "helm"
     ],
     "pop": 0.0213
    },
    {
     "slugs": [
      "moran",
      "chisato",
      "takina",
      "raven",
      "privaty"
     ],
     "pop": 0.0213
    },
    {
     "slugs": [
      "ade-agent-bunny",
      "raven",
      "moran",
      "red-hood",
      "privaty"
     ],
     "pop": 0.0213
    },
    {
     "slugs": [
      "grave",
      "moran",
      "red-hood",
      "raven",
      "privaty"
     ],
     "pop": 0.0213
    },
    {
     "slugs": [
      "tove",
      "ade-agent-bunny",
      "soda-twinkling-bunny",
      "dorothy-serendipity",
      "drake"
     ],
     "pop": 0.0213
    },
    {
     "slugs": [
      "cinderella",
      "rouge",
      "red-hood",
      "grave",
      "privaty"
     ],
     "pop": 0.0213
    },
    {
     "slugs": [
      "ade-agent-bunny",
      "miranda",
      "snow-white-heavy-arms",
      "moran",
      "eve"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "moran",
      "chisato",
      "takina",
      "ada",
      "helm"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "miranda",
      "chisato",
      "takina",
      "d-killer-wife",
      "ada"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "moran",
      "chisato",
      "laplace",
      "takina",
      "privaty"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "takina",
      "rouge",
      "chisato",
      "ada",
      "red-hood"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "raven",
      "chisato",
      "takina",
      "ada",
      "moran"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "chisato",
      "diesel-winter-sweets",
      "helm",
      "takina",
      "moran"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "chisato",
      "moran",
      "takina",
      "snow-white-heavy-arms",
      "helm"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "moran",
      "chisato",
      "takina",
      "laplace",
      "ada"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "snow-white-heavy-arms",
      "moran",
      "ade-agent-bunny",
      "raven",
      "privaty"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "raven",
      "rouge",
      "milk-blooming-bunny",
      "rosanna-chic-ocean",
      "privaty"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "moran",
      "ade-agent-bunny",
      "milk-blooming-bunny",
      "red-hood",
      "snow-white-heavy-arms"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "moran",
      "ade-agent-bunny",
      "snow-white-heavy-arms",
      "red-hood",
      "raven"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "moran",
      "ade-agent-bunny",
      "milk-blooming-bunny",
      "raven",
      "privaty"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "moran",
      "chisato",
      "takina",
      "milk-blooming-bunny",
      "ada"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "snow-white-heavy-arms",
      "rouge",
      "red-hood",
      "grave",
      "privaty"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "miranda",
      "ade-agent-bunny",
      "snow-white-heavy-arms",
      "rouge",
      "eve"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "chisato",
      "rouge",
      "snow-white-heavy-arms",
      "takina",
      "mihara-bonding-chain"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "chisato",
      "rouge",
      "cinderella",
      "takina",
      "red-hood"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "cinderella",
      "rouge",
      "chisato",
      "takina",
      "mihara-bonding-chain"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "moran",
      "chisato",
      "takina",
      "snow-white-heavy-arms",
      "ada"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "moran",
      "ade-agent-bunny",
      "cinderella",
      "snow-white-heavy-arms",
      "red-hood"
     ],
     "pop": 0.0106
    },
    {
     "slugs": [
      "raven",
      "rouge",
      "milk-blooming-bunny",
      "ade-agent-bunny",
      "privaty"
     ],
     "pop": 0.0106
    }
   ]
  },
  "Wind": {
   "raid": "Iron",
   "boss": "Iron",
   "unitPop": {
    "anchor-innocent-maid": 1,
    "liberalio": 1,
    "liter": 0.84,
    "mast-romantic-maid": 1,
    "scarlet-black-shadow": 1,
    "crown": 1,
    "asuka-wille": 1,
    "little-mermaid": 1,
    "delta-ninja-thief": 0.64,
    "cinderella": 0.98,
    "mana": 0.88,
    "ade-agent-bunny": 0.72,
    "rapi-red-hood": 0.99,
    "mihara-bonding-chain": 0.93,
    "tove": 0.94,
    "blanc": 0.65,
    "dorothy-serendipity": 0.92,
    "noir": 0.45,
    "drake": 0.93,
    "volume": 0.65,
    "grave": 0.63,
    "miranda": 0.9,
    "nayuta": 1,
    "maxwell": 0.61,
    "helm": 0.99,
    "d-killer-wife": 0.45,
    "rouge": 0.8,
    "sakura-bloom-in-summer": 0.44,
    "ludmilla-winter-owner": 0.43,
    "naga": 0.15,
    "guilty": 0.03,
    "alice": 0.01,
    "modernia": 0.01,
    "red-hood": 0.03,
    "soda-twinkling-bunny": 0.01
   },
   "comps": [
    {
     "slugs": [
      "miranda",
      "nayuta",
      "maxwell",
      "helm",
      "d-killer-wife"
     ],
     "pop": 1
    },
    {
     "slugs": [
      "maxwell",
      "miranda",
      "nayuta",
      "rouge",
      "helm"
     ],
     "pop": 0.88
    },
    {
     "slugs": [
      "miranda",
      "helm",
      "nayuta",
      "rouge",
      "sakura-bloom-in-summer"
     ],
     "pop": 0.44
    },
    {
     "slugs": [
      "miranda",
      "ludmilla-winter-owner",
      "nayuta",
      "helm",
      "d-killer-wife"
     ],
     "pop": 0.4
    },
    {
     "slugs": [
      "maxwell",
      "miranda",
      "nayuta",
      "rouge",
      "sakura-bloom-in-summer"
     ],
     "pop": 0.28
    },
    {
     "slugs": [
      "crown",
      "rapi-red-hood",
      "little-mermaid",
      "ludmilla-winter-owner",
      "naga"
     ],
     "pop": 0.28
    },
    {
     "slugs": [
      "cinderella",
      "rouge",
      "sakura-bloom-in-summer",
      "ade-agent-bunny",
      "mihara-bonding-chain"
     ],
     "pop": 0.24
    },
    {
     "slugs": [
      "miranda",
      "sakura-bloom-in-summer",
      "nayuta",
      "maxwell",
      "d-killer-wife"
     ],
     "pop": 0.2
    },
    {
     "slugs": [
      "miranda",
      "sakura-bloom-in-summer",
      "nayuta",
      "helm",
      "d-killer-wife"
     ],
     "pop": 0.16
    },
    {
     "slugs": [
      "cinderella",
      "rapi-red-hood",
      "ade-agent-bunny",
      "sakura-bloom-in-summer",
      "mihara-bonding-chain"
     ],
     "pop": 0.16
    },
    {
     "slugs": [
      "miranda",
      "helm",
      "ludmilla-winter-owner",
      "rouge",
      "nayuta"
     ],
     "pop": 0.08
    },
    {
     "slugs": [
      "crown",
      "asuka-wille",
      "little-mermaid",
      "rapi-red-hood",
      "naga"
     ],
     "pop": 0.08
    },
    {
     "slugs": [
      "cinderella",
      "rouge",
      "sakura-bloom-in-summer",
      "ade-agent-bunny",
      "ludmilla-winter-owner"
     ],
     "pop": 0.04
    },
    {
     "slugs": [
      "rapi-red-hood",
      "nayuta",
      "ludmilla-winter-owner",
      "helm",
      "red-hood"
     ],
     "pop": 0.04
    },
    {
     "slugs": [
      "cinderella",
      "grave",
      "rapi-red-hood",
      "sakura-bloom-in-summer",
      "mihara-bonding-chain"
     ],
     "pop": 0.04
    },
    {
     "slugs": [
      "miranda",
      "d-killer-wife",
      "helm",
      "nayuta",
      "mihara-bonding-chain"
     ],
     "pop": 0.04
    }
   ]
  }
 },
 "tierPop": {
  "cinderella-crystal-wave": 1
 },
 "fallbackSlugs": [
  "cinderella-crystal-wave"
 ]
};
