// Static portrait thumbnails, generated by scripts/gen-portrait-thumbs.ts
// (npm run thumbs) into web/public/img/portraits/<slug>-<tier>.webp. The
// manifest maps a CDN imageUrl to its slug; the site serves the local
// pre-cropped webp instead of downloading the full-res 256×512 art (~200KB)
// and canvas-downscaling it at runtime. Units without a generated thumbnail
// (e.g. freshly synced before the next thumbs run) fall back to the runtime
// canvas path in portraitThumb.ts.
import manifestJson from './portrait-manifest.json';

const URL_TO_SLUG = manifestJson as Record<string, string>;
const TIERS = [128, 256] as const;

// Local thumbnail URL for an imageUrl at a given CSS size — the smallest tier
// that still covers cssSize×dpr (so the browser never upscales). Null when no
// thumbnail exists for the unit.
export function manifestThumbUrl(
  imageUrl: string | null | undefined,
  cssSize: number,
): string | null {
  if (!imageUrl) return null;
  const slug = URL_TO_SLUG[imageUrl];
  if (!slug) return null;
  const dpr = Math.min(
    typeof window !== 'undefined' ? window.devicePixelRatio || 1 : 1,
    3,
  );
  const need = Math.round(cssSize * dpr);
  const tier = TIERS.find((t) => t >= need) ?? TIERS[TIERS.length - 1];
  return `${import.meta.env.BASE_URL}img/portraits/${slug}-${tier}.webp`;
}
