import { useEffect, useMemo, useRef, useState } from 'react';
import type { PointerEvent as ReactPointerEvent } from 'react';
import charactersJson from '../../data/characters.json';
import archetypeTagsJson from '../../data/archetype-tags.json';
import type { DataFile } from '../../src/types';
import { useIconThumbs } from './useIconThumbs';
import { usePortraitThumbs } from './usePortraitThumbs';
import type { AuthUser } from './auth';

const data = charactersJson as unknown as DataFile;

// Kit-role archetype tags (what a unit's kit DOES — buffer, reload buffer,
// distributed damage, …). Generated by scripts/build-archetype-tags.ts; see
// docs/data/archetype-tags.md. The `vocabulary` block carries the player-facing
// label + blurb so the UI never hardcodes them.
type ArchetypeTagsFile = {
  vocabulary: Record<string, { label: string; blurb: string; group: string }>;
  tags: Record<string, string[]>;
};
const archetypeData = archetypeTagsJson as unknown as ArchetypeTagsFile;

// Pills are bucketed into groups (Stat Buffs / Damage Buffs / Ally Filters /
// Burst Support / Role) for the filter panel. Group order = first appearance in
// the vocabulary and pill order within a group = vocabulary insertion order; both
// mirror the TAG_DEFS order in the build script, so the panel reads top-to-bottom
// in the same order the rules are defined there.
type ArchetypeOption = { id: string; label: string; blurb: string };
const ARCHETYPE_GROUPS: { group: string; options: ArchetypeOption[] }[] =
  (() => {
    const byGroup = new Map<string, ArchetypeOption[]>();
    for (const [id, v] of Object.entries(archetypeData.vocabulary)) {
      if (!byGroup.has(v.group)) byGroup.set(v.group, []);
      byGroup.get(v.group)!.push({ id, label: v.label, blurb: v.blurb });
    }
    return [...byGroup.entries()].map(([group, options]) => ({
      group,
      options,
    }));
  })();

export interface TeamBuilderProps {
  user: AuthUser | null;
  onSaveTeam: (slugs: (string | null)[]) => Promise<void>;
  // Returns a warning message (and does NOT switch tabs) when the team includes a
  // sim-unsupported nikke; returns null and switches to the Sim tab on success.
  onCopyToSim: (slugs: (string | null)[]) => string | null;
  onTeamChange: (slugs: (string | null)[]) => void;
}

// Icon-only filter row: a set of square icon buttons. Each button toggles on/off
// (multi-select). When no buttons in a row are selected, the filter is inactive
// (all values pass). When one or more are selected, only characters matching at
// least one selected value pass.
type FilterRowProps = {
  label: string;
  options: {
    id: string;
    icon: string;
    match?: (value: string) => boolean;
    imgStyle?: React.CSSProperties;
  }[];
  selected: Set<string>;
  onToggle: (id: string) => void;
  thumbs: Record<string, string>;
};

function FilterRow({
  label,
  options,
  selected,
  onToggle,
  thumbs,
}: FilterRowProps) {
  return (
    <div className='teambuilder-filter-row'>
      <span className='teambuilder-filter-label'>{label}</span>
      <div className='teambuilder-filter-icons'>
        {options.map((opt) => {
          const active = selected.has(opt.id);
          const src = `/nikke-icons/${opt.icon}`;
          // Tag icons that should keep their original colors when selected
          // (skip the brightness(0) filter). Weapon and burst icons are
          // monochrome but need to stay visible on the accent background.
          const isColored =
            opt.icon.startsWith('code_') ||
            opt.icon.startsWith('class_') ||
            opt.icon.startsWith('man_') ||
            opt.icon.startsWith('weapon_') ||
            opt.icon.startsWith('burst_');
          return (
            <button
              key={opt.id}
              className={'teambuilder-icon-btn' + (active ? ' on' : '')}
              onClick={() => onToggle(opt.id)}
              title={opt.id}
              aria-pressed={active}
            >
              <img
                src={src.endsWith('.svg') ? src : (thumbs[src] ?? src)}
                alt={opt.id}
                draggable={false}
                data-colored={isColored ? '' : undefined}
                style={opt.imgStyle}
              />
            </button>
          );
        })}
      </div>
    </div>
  );
}

// Filter option definitions — each option maps to an icon file and a match
// function. For manufacturers, the base icon matches both the base name and
// the "Overspec" variant (e.g. Elysion matches "Elysion" and "Elysion Overspec").
const WEAPON_OPTIONS = [
  { id: 'AR', icon: 'weapon_ar.png' },
  { id: 'SMG', icon: 'weapon_smg.png' },
  { id: 'SG', icon: 'weapon_sg.png' },
  { id: 'MG', icon: 'weapon_mg.png' },
  { id: 'SR', icon: 'weapon_sr.png' },
  { id: 'RL', icon: 'weapon_rl.png' },
];

const BURST_OPTIONS = [
  { id: 'I', icon: 'burst_1.svg', imgStyle: { padding: 8 } },
  { id: 'II', icon: 'burst_2.svg', imgStyle: { padding: 8 } },
  { id: 'III', icon: 'burst_3.svg', imgStyle: { padding: 8 } },
];
// Λ burst characters are included in every burst filter selection (no dedicated
// Λ icon exists, and they're rare enough that a separate filter isn't needed).

const ICON_PAD: React.CSSProperties = { padding: 4 };

const CLASS_OPTIONS = [
  { id: 'Attacker', icon: 'class_attacker.webp', imgStyle: ICON_PAD },
  { id: 'Defender', icon: 'class_defender.webp', imgStyle: ICON_PAD },
  { id: 'Supporter', icon: 'class_support.webp', imgStyle: ICON_PAD },
];

const ELEMENT_OPTIONS = [
  { id: 'Fire', icon: 'code_fire.svg', imgStyle: ICON_PAD },
  { id: 'Water', icon: 'code_water.svg', imgStyle: ICON_PAD },
  { id: 'Wind', icon: 'code_wind.svg', imgStyle: ICON_PAD },
  { id: 'Electric', icon: 'code_electric.svg', imgStyle: ICON_PAD },
  { id: 'Iron', icon: 'code_iron.svg', imgStyle: ICON_PAD },
];

// Base manufacturer names — selecting one also matches its Overspec variant.
// Ordered: Elysion, Missilis, Tetra, Pilgrim, Abnormal
const MANUFACTURER_OPTIONS = [
  {
    id: 'Elysion',
    icon: 'man_elysion.webp',
    imgStyle: ICON_PAD,
    match: (v: string) => v === 'Elysion' || v === 'Elysion Overspec',
  },
  {
    id: 'Missilis',
    icon: 'man_missilis.webp',
    imgStyle: ICON_PAD,
    match: (v: string) => v === 'Missilis' || v === 'Missilis Overspec',
  },
  {
    id: 'Tetra',
    icon: 'man_tetra.webp',
    imgStyle: ICON_PAD,
    match: (v: string) => v === 'Tetra' || v === 'Tetra Overspec',
  },
  {
    id: 'Pilgrim',
    icon: 'man_pilgrim.webp',
    imgStyle: ICON_PAD,
    match: (v: string) => v === 'Pilgrim',
  },
  {
    id: 'Abnormal',
    icon: 'man_abnormal.webp',
    imgStyle: ICON_PAD,
    match: (v: string) => v === 'Abnormal',
  },
];

// All filter icon URLs — collected once so useIconThumbs can pre-downscale
// them. SVGs are excluded: the browser rasterizes vectors natively at device
// resolution (FilterRow uses the raw URL for them), so pre-downscaling would
// only soften them.
const FILTER_ICON_URLS = [
  ...WEAPON_OPTIONS,
  ...BURST_OPTIONS,
  ...CLASS_OPTIONS,
  ...ELEMENT_OPTIONS,
  ...MANUFACTURER_OPTIONS,
]
  .map((opt) => `/nikke-icons/${opt.icon}`)
  .filter((url) => !url.endsWith('.svg'));

function emptySet(): Set<string> {
  return new Set();
}

// Drag-to-reorder hook (copied from App.tsx team sim page).
function useDragReorder(
  onMove: (from: number, to: number) => void,
  onTap?: (i: number) => void,
) {
  const items = useRef(new Map<number, HTMLElement>());
  const drag = useRef<{
    pointerId: number;
    startX: number;
    startY: number;
    index: number;
    moved: boolean;
  } | null>(null);
  const [dragIndex, setDragIndex] = useState<number | null>(null);

  const register = (i: number) => (el: HTMLElement | null) => {
    if (el) items.current.set(i, el);
    else items.current.delete(i);
  };

  const nearest = (x: number, y: number): number => {
    let best = -1;
    let bestDist = Infinity;
    items.current.forEach((el, idx) => {
      const r = el.getBoundingClientRect();
      const dx = r.left + r.width / 2 - x;
      const dy = r.top + r.height / 2 - y;
      const d = dx * dx + dy * dy;
      if (d < bestDist) {
        bestDist = d;
        best = idx;
      }
    });
    return best;
  };

  const handleProps = (
    i: number,
    onItemTap?: (i: number, e: ReactPointerEvent) => void,
  ) => ({
    onPointerDown: (e: ReactPointerEvent) => {
      if (e.button && e.button !== 0) return;
      drag.current = {
        pointerId: e.pointerId,
        startX: e.clientX,
        startY: e.clientY,
        index: i,
        moved: false,
      };
      e.currentTarget.setPointerCapture(e.pointerId);
    },
    onPointerMove: (e: ReactPointerEvent) => {
      const st = drag.current;
      if (!st || e.pointerId !== st.pointerId) return;
      if (!st.moved) {
        const dx = e.clientX - st.startX;
        const dy = e.clientY - st.startY;
        if (dx * dx + dy * dy < 36) return;
        st.moved = true;
        setDragIndex(st.index);
      }
      const target = nearest(e.clientX, e.clientY);
      if (target >= 0 && target !== st.index) {
        onMove(st.index, target);
        st.index = target;
        setDragIndex(target);
      }
    },
    onPointerUp: (e: ReactPointerEvent) => {
      const st = drag.current;
      if (!st || e.pointerId !== st.pointerId) return;
      if (!st.moved) {
        if (onItemTap) onItemTap(st.index, e);
        else if (onTap) onTap(st.index);
      }
      drag.current = null;
      setDragIndex(null);
    },
    onPointerCancel: () => {
      drag.current = null;
      setDragIndex(null);
    },
  });

  return { register, handleProps, dragIndex };
}

export function TeamBuilderPage({
  user,
  onSaveTeam,
  onCopyToSim,
  onTeamChange,
}: TeamBuilderProps) {
  const [savedFlash, setSavedFlash] = useState(false);
  const [copyWarning, setCopyWarning] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [weaponFilter, setWeaponFilter] = useState<Set<string>>(emptySet);
  const [burstFilter, setBurstFilter] = useState<Set<string>>(emptySet);
  const [classFilter, setClassFilter] = useState<Set<string>>(emptySet);
  const [elementFilter, setElementFilter] = useState<Set<string>>(emptySet);
  const [manufacturerFilter, setManufacturerFilter] =
    useState<Set<string>>(emptySet);
  const [archetypeFilter, setArchetypeFilter] = useState<Set<string>>(emptySet);

  // Team slots: 5 slots, each holds a character slug or null (empty).
  const [teamSlots, setTeamSlots] = useState<(string | null)[]>([
    null,
    null,
    null,
    null,
    null,
  ]);

  // Report team slots up to App.tsx so header buttons can act on them.
  useEffect(() => {
    onTeamChange(teamSlots);
  }, [teamSlots, onTeamChange]);

  // Drag-to-reorder for team slots.
  const moveSlot = (from: number, to: number) => {
    setTeamSlots((prev) => {
      const next = [...prev];
      const [item] = next.splice(from, 1);
      next.splice(to, 0, item);
      return next;
    });
  };
  const teamReorder = useDragReorder(moveSlot);

  // Add a character to the next empty slot. If already in the team, remove them.
  const toggleTeamSlot = (slug: string) => {
    setCopyWarning(null);
    setTeamSlots((prev) => {
      // If already in the team, remove them
      const existingIdx = prev.indexOf(slug);
      if (existingIdx >= 0) {
        const next = [...prev];
        next[existingIdx] = null;
        return next;
      }
      // Find the next empty slot
      const emptyIdx = prev.indexOf(null);
      if (emptyIdx < 0) return prev; // team is full
      const next = [...prev];
      next[emptyIdx] = slug;
      return next;
    });
  };

  const removeFromSlot = (idx: number) => {
    setCopyWarning(null);
    setTeamSlots((prev) => {
      const next = [...prev];
      next[idx] = null;
      return next;
    });
  };

  const clearTeam = () => {
    setTeamSlots([null, null, null, null, null]);
    setCopyWarning(null);
  };

  const hasTeam = teamSlots.some((s) => s !== null);

  const handleSaveTeam = async () => {
    if (!hasTeam) return;
    const names = teamSlots
      .filter(Boolean)
      .map((s) => data.characters[s!].name);
    const defaultName = names.slice(0, 2).join(' / ') || 'My team';
    const name = window.prompt('Save team as:', defaultName);
    if (!name?.trim()) return;
    try {
      await onSaveTeam(teamSlots);
      setSavedFlash(true);
      setTimeout(() => setSavedFlash(false), 1500);
    } catch (e) {
      window.alert(`Save failed: ${(e as Error).message ?? e}`);
    }
  };

  const handleCopyToSim = () => {
    if (!hasTeam) return;
    setCopyWarning(onCopyToSim(teamSlots));
  };

  // Pre-downscale filter icons (40px CSS) and card mini-icons (18px CSS) via
  // stepped-halving so the browser never aliases them at render time.
  const filterThumbs = useIconThumbs(FILTER_ICON_URLS, 40);
  const miniIconUrls = useMemo(() => {
    const urls = new Set<string>();
    Object.values(data.characters).forEach((c) => {
      // Raster sources only — SVGs (element/burst) are rendered natively by
      // the browser at device resolution; canvas-rasterizing them here would
      // only blur them.
      urls.add(`/nikke-icons/weapon_${c.weapon.toLowerCase()}.png`);
      // Class icon: 'Supporter' → 'class_support.webp' (file named without 'er')
      const classFile =
        c.class === 'Supporter' ? 'support' : c.class.toLowerCase();
      urls.add(`/nikke-icons/class_${classFile}.webp`);
    });
    return Array.from(urls);
  }, []);
  const miniThumbs = useIconThumbs(miniIconUrls, 18);

  const toggle = (current: Set<string>, setter: (s: Set<string>) => void) => {
    return (id: string) => {
      const next = new Set(current);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      setter(next);
    };
  };

  const characters = useMemo(() => {
    const all = Object.values(data.characters);
    const q = search.toLowerCase();
    return all.filter((c) => {
      // Text search — slug, name, or approved community nickname
      if (q) {
        const textMatch =
          c.slug.includes(q) ||
          c.name.toLowerCase().includes(q) ||
          (c.nicknames ?? []).some((n) => n.includes(q));
        if (!textMatch) return false;
      }
      // Weapon filter
      if (weaponFilter.size > 0 && !weaponFilter.has(c.weapon)) return false;
      // Burst filter — Λ burst characters are always included (no dedicated filter)
      if (burstFilter.size > 0 && c.burst !== 'Λ' && !burstFilter.has(c.burst))
        return false;
      // Class filter
      if (classFilter.size > 0 && !classFilter.has(c.class)) return false;
      // Element filter
      if (elementFilter.size > 0 && !elementFilter.has(c.element)) return false;
      // Manufacturer filter — use the match function if present, else exact match
      if (manufacturerFilter.size > 0) {
        const matched = MANUFACTURER_OPTIONS.some(
          (opt) =>
            manufacturerFilter.has(opt.id) &&
            (opt.match
              ? opt.match(c.manufacturer ?? '')
              : c.manufacturer === opt.id),
        );
        if (!matched) return false;
      }
      // Archetype filter — OR within the row (a unit passes if it carries ANY
      // selected tag), AND with the other rows. Units with no tags only pass
      // while the row is inactive.
      if (archetypeFilter.size > 0) {
        const unitTags = archetypeData.tags[c.slug] ?? [];
        if (!unitTags.some((t) => archetypeFilter.has(t))) return false;
      }
      return true;
    });
  }, [
    search,
    weaponFilter,
    burstFilter,
    classFilter,
    elementFilter,
    manufacturerFilter,
    archetypeFilter,
  ]);

  // Pre-downscale character portraits (120px CSS card width) using the same
  // stepped-halving pipeline as the Team Sim page. Computed from all characters
  // (not filtered) so the hook call order stays stable across filter changes.
  const allPortraitUrls = useMemo(
    () =>
      Object.values(data.characters)
        .map((c) => c.imageUrl)
        .filter(Boolean) as string[],
    [],
  );
  const portraitThumbs = usePortraitThumbs(allPortraitUrls, 120);

  // Portrait thumbs for team slots (120px CSS — same as character cards below)
  const teamSlotUrls = useMemo(
    () => teamSlots.filter(Boolean) as string[],
    [teamSlots],
  );
  const teamSlotThumbs = usePortraitThumbs(teamSlotUrls, 120);

  const total = Object.values(data.characters).length;
  const showing = characters.length;
  const anyActive =
    search !== '' ||
    weaponFilter.size > 0 ||
    burstFilter.size > 0 ||
    classFilter.size > 0 ||
    elementFilter.size > 0 ||
    manufacturerFilter.size > 0 ||
    archetypeFilter.size > 0;

  return (
    <section className='calc-tab teambuilder-page'>
      <p className='muted'>
        Browse all NIKKEs and filter by weapon, burst, class, element,
        manufacturer, or kit role. Tap an icon or role pill to toggle it on —
        multiple selections within a row are OR'd together; rows are AND'd.
        Click a character card to add them to your team.
      </p>

      {/* Team slots — 5 boxes that fill in as you click characters below */}
      <div className='teambuilder-team'>
        <div className='roster-slots'>
          {teamSlots.map((slug, i) => {
            const c = slug ? data.characters[slug] : null;
            return (
              <button
                key={i}
                type='button'
                ref={teamReorder.register(i)}
                className={
                  'team-chip roster-slot' +
                  (slug ? ' active' : '') +
                  (teamReorder.dragIndex === i ? ' dragging' : '')
                }
                title={c?.name ?? `slot ${i + 1}`}
                onClick={() => (slug ? removeFromSlot(i) : undefined)}
                {...teamReorder.handleProps(i)}
              >
                {c?.imageUrl ? (
                  <img
                    src={teamSlotThumbs[c.imageUrl] ?? c.imageUrl}
                    alt={c.name}
                    draggable={false}
                  />
                ) : (
                  <span className='chip-empty'>+</span>
                )}
                {slug && (
                  <span
                    className='chip-x'
                    role='button'
                    aria-label='remove'
                    onClick={(e) => {
                      e.stopPropagation();
                      removeFromSlot(i);
                    }}
                  >
                    ×
                  </span>
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* Team management actions — below the team portraits */}
      {hasTeam && (
        <div className='teambuilder-actions'>
          <button className='teambuilder-clear' onClick={clearTeam}>
            Clear team
          </button>
          {user && (
            <button className='teambuilder-action' onClick={handleSaveTeam}>
              {savedFlash ? '✓ Saved' : '💾 Save team'}
            </button>
          )}
          <button className='teambuilder-action' onClick={handleCopyToSim}>
            ✎ Copy to Sim
          </button>
        </div>
      )}

      {copyWarning && (
        <div className='teambuilder-warning' role='alert'>
          {copyWarning}
        </div>
      )}

      <div className='teambuilder-filters'>
        {/* Left — the stat-axis icon rows */}
        <div className='teambuilder-filters-stat'>
          <FilterRow
            label='Weapon'
            options={WEAPON_OPTIONS}
            selected={weaponFilter}
            onToggle={toggle(weaponFilter, setWeaponFilter)}
            thumbs={filterThumbs}
          />
          <FilterRow
            label='Burst'
            options={BURST_OPTIONS}
            selected={burstFilter}
            onToggle={toggle(burstFilter, setBurstFilter)}
            thumbs={filterThumbs}
          />
          <FilterRow
            label='Class'
            options={CLASS_OPTIONS}
            selected={classFilter}
            onToggle={toggle(classFilter, setClassFilter)}
            thumbs={filterThumbs}
          />
          <FilterRow
            label='Element'
            options={ELEMENT_OPTIONS}
            selected={elementFilter}
            onToggle={toggle(elementFilter, setElementFilter)}
            thumbs={filterThumbs}
          />
          <FilterRow
            label='Manufacturer'
            options={MANUFACTURER_OPTIONS}
            selected={manufacturerFilter}
            onToggle={toggle(manufacturerFilter, setManufacturerFilter)}
            thumbs={filterThumbs}
          />
        </div>

        {/* Right — kit-role archetype pills (fill the space beside the icon
            rows), bucketed into groups. Labels + blurbs + group names all come
            from the generated vocabulary; nothing is hardcoded here. */}
        <div className='teambuilder-archetypes'>
          {ARCHETYPE_GROUPS.map(({ group, options }) => (
            <div className='teambuilder-archetype-group' key={group}>
              <span className='teambuilder-archetype-group-label'>{group}</span>
              <div className='teambuilder-archetype-pills'>
                {options.map((opt) => {
                  const active = archetypeFilter.has(opt.id);
                  return (
                    <button
                      key={opt.id}
                      type='button'
                      className={'teambuilder-pill' + (active ? ' on' : '')}
                      onClick={() =>
                        toggle(archetypeFilter, setArchetypeFilter)(opt.id)
                      }
                      title={opt.blurb}
                      aria-pressed={active}
                    >
                      {opt.label}
                    </button>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className='teambuilder-search'>
        <input
          type='text'
          placeholder='Search by name or nickname…'
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        {search && (
          <button
            className='teambuilder-search-clear'
            onClick={() => setSearch('')}
            aria-label='Clear search'
          >
            ×
          </button>
        )}
      </div>

      {anyActive && (
        <div className='teambuilder-count muted'>
          Showing {showing} of {total} NIKKEs
          <button
            className='teambuilder-clear'
            onClick={() => {
              setSearch('');
              setWeaponFilter(emptySet());
              setBurstFilter(emptySet());
              setClassFilter(emptySet());
              setElementFilter(emptySet());
              setManufacturerFilter(emptySet());
              setArchetypeFilter(emptySet());
            }}
          >
            Clear all
          </button>
        </div>
      )}

      <div className='teambuilder-grid'>
        {characters.map((c) => {
          const weaponSrc = `/nikke-icons/weapon_${c.weapon.toLowerCase()}.png`;
          const elementSrc = `/nikke-icons/code_${c.element.toLowerCase()}.svg`;
          const burstSrc = `/nikke-icons/burst_${c.burst === 'I' ? '1' : c.burst === 'II' ? '2' : '3'}.svg`;
          // Class icon: 'Supporter' → 'class_support.webp' (file named without 'er')
          const classFile =
            c.class === 'Supporter' ? 'support' : c.class.toLowerCase();
          const classSrc = `/nikke-icons/class_${classFile}.webp`;
          const inTeam = teamSlots.includes(c.slug);
          return (
            <button
              key={c.slug}
              type='button'
              className={`teambuilder-card${inTeam ? ' in-team' : ''}${c.simSupported ? '' : ' unsupported'}`}
              onClick={() => toggleTeamSlot(c.slug)}
              title={
                c.simSupported
                  ? inTeam
                    ? `${c.name} — click to remove from team`
                    : `${c.name} — click to add to team`
                  : `${c.name} — not in the sim yet (browsable here in Team Builder only)`
              }
            >
              <div className='teambuilder-portrait'>
                {c.imageUrl ? (
                  <img
                    src={portraitThumbs[c.imageUrl] ?? c.imageUrl}
                    alt={c.name}
                    loading='lazy'
                  />
                ) : (
                  <span className='teambuilder-portrait-empty'>?</span>
                )}
                {!c.simSupported && (
                  <span className='teambuilder-unsupported-badge'>
                    Not In Sim
                  </span>
                )}
              </div>
              <div className='teambuilder-card-info'>
                <span className='teambuilder-card-name'>{c.name}</span>
                <div className='teambuilder-card-icons'>
                  <img
                    src={miniThumbs[weaponSrc] ?? weaponSrc}
                    alt={c.weapon}
                    title={c.weapon}
                    className='teambuilder-mini-icon'
                  />
                  <img
                    src={elementSrc}
                    alt={c.element}
                    title={c.element}
                    className='teambuilder-mini-icon'
                  />
                  <img
                    src={burstSrc}
                    alt={`Burst ${c.burst}`}
                    title={`Burst ${c.burst}`}
                    className='teambuilder-mini-icon'
                  />
                  <img
                    src={miniThumbs[classSrc] ?? classSrc}
                    alt={c.class}
                    title={c.class}
                    className='teambuilder-mini-icon'
                  />
                </div>
              </div>
            </button>
          );
        })}
      </div>

      {characters.length === 0 && (
        <div className='teambuilder-empty muted'>
          No NIKKEs match the selected filters.
        </div>
      )}
    </section>
  );
}
