// FILE: src/skills/scale.ts

// Skill-level scaling. blablalink roledata gives every skill-description
// placeholder as a 10-entry array (index = skill level - 1). The parser reads
// max-level prose, so to run a skill at level L we match each parsed number
// against index 9 of the arrays and substitute index L-1. Durations are never
// scaled (they are level-constant in practice; matching them would risk
// scaling "for 10 sec" that collides with a 10% value).
import type { Block, EffectDef, SkillSlot } from './types.js';

export interface SlotLevelArrays {
  skill1: number[][];
  skill2: number[][];
  burst: number[][];
}
export interface SkillLevels {
  skill1: number;
  skill2: number;
  burst: number;
}

export function scaleBlocks(
  blocks: Block[],
  arrays: SlotLevelArrays,
  levels: SkillLevels,
  warnings: string[]
): Block[] {
  const missing = new Set<string>();

  const scaleVal = (v: number, slot: SkillSlot): number => {
    const lvl = levels[slot];
    if (lvl >= 10 || v === 0) return v;
    const abs = Math.abs(v);
    const arr = (arrays[slot] ?? []).find((a) => Math.abs(a[9] - abs) < 0.005);
    if (!arr) {
      missing.add(`${slot}: no level table match for ${v} — kept at max-level value`);
      return v;
    }
    return arr[lvl - 1] * Math.sign(v);
  };

  const scaleEffect = (e: EffectDef, slot: SkillSlot): EffectDef => {
    switch (e.kind) {
      case 'buff': return { ...e, value: scaleVal(e.value, slot) };
      case 'flatDamage': return { ...e, atkPct: scaleVal(e.atkPct, slot) };
      case 'dot': return { ...e, atkPct: scaleVal(e.atkPct, slot) };
      case 'burstCdr': return { ...e, seconds: scaleVal(e.seconds, slot) };
      case 'escalating': return { ...e, steps: e.steps.map((s) => scaleEffect(s, slot)) };
      default: return e;
    }
  };

  const scaled = blocks.map((b) =>
    levels[b.slot] >= 10 ? b : { ...b, effects: b.effects.map((e) => scaleEffect(e, b.slot)) }
  );
  warnings.push(...missing);
  return scaled;
}


// FILE: src/skills/index.ts

// Resolves a character's skill Blocks from its hand-written/materialized
// override, then scales values to the requested skill levels. The engine NEVER
// parses skill prose at runtime: every roster unit's override is the complete
// description of its kit (all three slots), produced offline by the kit parser
// (scripts/lib/kit-parser.ts via scripts/materialize-overrides.ts) or authored
// via /kit-parse. Pure — no filesystem access, so it runs in the browser too.
// Node callers get overrides from ./overrides-node.ts; the web app bundles them
// via import.meta.glob.
import type { CharacterData } from '../types.js';
import { scaleBlocks, type SkillLevels, type SlotLevelArrays } from './scale.js';
import type { Block, CharacterSkills, ConsolidationConfig, SkillSlot, UnmodeledText } from './types.js';

const SLOTS: SkillSlot[] = ['skill1', 'skill2', 'burst'];

export interface OverrideFile {
  note?: string;
  // Verbatim kit-text lines NOT represented in blocks (all three keys present,
  // empty arrays OK). The auditable "no silent drops" record; reasons/audit
  // stay in `note`. Hand-authored slots predating 2026-07-16 may still have
  // empty arrays with skips documented in `note` only (backfill pending).
  unmodeled?: UnmodeledText;
  // Display-only modeling caveats surfaced as runtime warnings (replaces the
  // old runtime-parser warnings channel). Convention: "<slot>: <message>".
  caveats?: string[];
  // Display-only, owner-facing plain-English description of what this kit
  // actually does (skill1/skill2/burst), generated by the `audit-kit`
  // reconciling judge and carried over from its fix brief when the brief is
  // enacted. For sanity-checking the model against intuition, not engine input.
  kitDescription?: string;
  modes?: string[]; // user-selectable kit modes (first = default)
  // this unit's attacks are Pierce-tagged (kit says so), so Pierce Damage ▲
  // buffs feed its Damage Up bucket (Q10). Set only on kit-confirmed carriers.
  hasPierce?: boolean; // always pierce (e.g. red-hood)
  pierceModes?: string[]; // pierce only in these modes (e.g. CCW: ["Snipe"])
  // hand-measured corrections to DB weapon data (e.g. real SR fire cycle =
  // charge + bolt recovery, where the DB only records the charge time)
  charFixes?: { chargeFrames?: number; reloadFrames?: number; burstCooldownSec?: number; noBoltRecovery?: boolean; pullsPerSec?: number };
  // Pellet-consolidation mode (dorothy-S: "after landing N pellets, for K rounds → pellet count fixed at 1
  // + high core + Pierce + attack-dmg"). Range-gated to near (where the boss affords the trigger). MEASURED
  // gate; the "80 landed on the small core" story is interpretive. See open-questions A26.
  consolidation?: ConsolidationConfig;
  // named live resource pools (soda-twinkling-bunny's Golden Chip) — see CharacterSkills.resources
  resources?: { name: string; initial: number; min?: number; max?: number }[];
  burstSnapshotsPreFb?: boolean;
  // All three slots are REQUIRED for roster units (validated by
  // scripts/validate-overrides.ts); typed optional only so partially-built
  // objects can be handled during materialization.
  skill1?: Block[];
  skill2?: Block[];
  burst?: Block[];
}

export const MAX_SKILL_LEVELS: SkillLevels = { skill1: 10, skill2: 10, burst: 10 };

export function resolveSkills(
  char: CharacterData,
  override?: OverrideFile,
  scaling?: { arrays: SlotLevelArrays; levels: SkillLevels }
): CharacterSkills {
  if (!override) {
    // Synthetic units with a genuinely empty kit (e.g. the dpschart no-op
    // controls) have no override file and no prose — zero blocks by design.
    if (SLOTS.every((s) => !char.skills[s]?.trim())) {
      return { blocks: [], warnings: [] };
    }
    throw new Error(
      `no skill override for "${char.slug}" — the engine does not parse skill prose at runtime; ` +
        `run \`npx tsx scripts/materialize-overrides.ts --write ${char.slug}\` or author one via /kit-parse`
    );
  }

  const warnings: string[] = [...(override.caveats ?? [])];
  const bySlot: Record<SkillSlot, Block[]> = { skill1: [], skill2: [], burst: [] };
  for (const slot of SLOTS) {
    const defined = override[slot];
    if (!Array.isArray(defined)) {
      throw new Error(
        `override for "${char.slug}" is missing "${slot}" — overrides must define all three skill ` +
          `slots (re-run \`npx tsx scripts/materialize-overrides.ts --write ${char.slug}\`)`
      );
    }
    bySlot[slot] = defined.map((b) => ({ ...b, slot }));
  }

  let blocks = SLOTS.flatMap((s) => bySlot[s]);
  if (scaling && SLOTS.some((s) => scaling.levels[s] < 10)) {
    blocks = scaleBlocks(blocks, scaling.arrays, scaling.levels, warnings);
  }

  return {
    blocks,
    warnings,
    unmodeled: override.unmodeled,
    modes: override.modes,
    hasPierce: override.hasPierce,
    burstSnapshotsPreFb: override.burstSnapshotsPreFb,
    pierceModes: override.pierceModes,
    consolidation: override.consolidation,
    resources: override.resources,
  };
}


// FILE: src/engine/sg-geometry.ts

// Accuracy-circle geometry — the px calibration (docs/data/sg-calc/) turned into
// core-hit-fraction and SG pellet-landing primitives, so those quantities are
// GEOMETRICALLY grounded from a unit's datamined accuracy_circle_scale + the boss
// range band, instead of owner-chosen tables and an abstract free-parameter reticle.
//
// ⚑ APPROXIMATION BASELINE — every constant here is a principled approximation, NOT
// measured-truth (see docs/data/sg-calc/DERIVATION.md §"These numbers are approximations"
// and accuracy-circle-calibration.json approximationCaveat). They may FILL unmeasured
// bands and GROUND free parameters, but must NEVER refit a measured constant
// (hard-constraint #3). Consumers land behind ENV flags, default matching current
// behaviour, until the board A/B says a workstream helps. See
// docs/data/sg-calc/IMPLEMENTATION-PLAN.md.

// scale → on-screen accuracy-circle diameter in px, at scope-lock resolution 2622×1206.
// PROPORTIONAL (offset≈0), R²=0.9999 from 3 independent BLOOM-PEAK measurements
// (AR scarlet 75→48px, SMG lm 110→71.5px, SG noir 250→162px). accuracy_circle_scale IS the
// fully-bloomed reticle diameter — the reticle pulses on the fire cadence between a contracted
// floor and this peak, and the peak is the anchor → no dead zone. The old 0.751·scale−25.2 offset
// was a bloom-phase artifact (the earlier AR 29px / SMG 60px were mid-bloom snapshots); re-measuring
// every class at its peak makes the map proportional. px/scale is uniform: 48/75=0.640, 71.5/110=0.650,
// 162/250=0.648. (The AR contracted floor ~29px ≈ the boss core, which is why high HR ≈ all-core.)
export const CIRCLE_PX_K = 0.648;
export const CIRCLE_PX_C = 0;

// range → boss-core diameter in px. Inverse-with-offset (perspective projection:
// apparent size ∝ 1/(distance + camera-offset)), R²=0.93; the ~47 offset is the
// camera-to-shooter distance. FORM robustly selected by the owner range bounds; k,c
// ride on fuzzy range midpoints (±~10%) and would be pinned exactly by one hard
// range measurement (open owner ruling in the implementation plan).
export const CORE_PX_K = 2100;
export const CORE_PX_C = 47;

// Datamined per-weapon-class accuracy_circle_scale (the class exemplars the px
// calibration was fit against). Mirrors sim.ts HR_CORE_CIRCLE. MG/SR/RL have no
// accuracy-circle model here → geometry does not touch their core rate.
export const ACCURACY_CIRCLE_SCALE: Record<string, number> = { AR: 75, SMG: 110, SG: 250 };

// Measured boss-core diameter per range band (px), hand-outlined on the Noir SG study
// (noir-sg-bands.json). The boss is the SAME physical union raid boss across element
// assignments (owner) → these transport across comps. Equivalent to coreDpx() at the
// calibration's impliedRanges (near 20.7, mid 28.0, midfar 52.9, far 76.4) by construction.
export const BAND_CORE_PX: Record<string, number> = { near: 31, mid: 28, midfar: 21, far: 17 };

// Hand-outlined SG pellet HIT fraction per band (noir-sg-bands.json): the fraction of the
// fixed D=162 spread circle covered by the boss body = expected fraction of pellets that land.
// Declines cleanly with range as the boss shrinks inside the fixed spread circle.
export const BAND_SG_HIT_FRAC: Record<string, number> = {
  near: 0.797,
  mid: 0.71,
  midfar: 0.634,
  far: 0.465,
};

// scale → accuracy-circle diameter in px (offset is 0 now, so Math.max is vestigial — kept harmless).
export function circleDpx(scale: number): number {
  return Math.max(0, CIRCLE_PX_K * scale + CIRCLE_PX_C);
}

// range → boss-core diameter in px.
export function coreDpx(range: number): number {
  return CORE_PX_K / (range + CORE_PX_C);
}

// range = inverse of coreDpx (for the continuous-range path / cross-checks).
export function rangeFromCoreDpx(coreD: number): number {
  return CORE_PX_K / coreD - CORE_PX_C;
}

// Concentric core inside the accuracy circle ⇒ fraction of shots on the core ≈ area ratio.
// Clamped to 1 (the core cannot be more than fully covered).
export function coreFracGeo(coreD: number, circleD: number): number {
  if (circleD <= 0) return 1;
  const r = coreD / circleD;
  return Math.min(1, r * r);
}

// Accuracy-circle diameter at a given hit rate, using the SAME fractional shrink the
// HRCORE reticle model applies (circle(hr) = circle(0) · max(FLOOR, 1 − s·hr)).
export function circleDpxAtHr(
  scale: number,
  hr: number,
  slope: number,
  floorFrac: number,
): number {
  const frac = Math.max(floorFrac, 1 - slope * Math.max(0, hr));
  return circleDpx(scale) * frac;
}

// ── Center-weighted pellet-landing model (CENTER-WEIGHTED-PELLET-SPEC.md) ────────────────────────
// Pellet impacts are a 2D isotropic Gaussian cone centered on the aim point, NOT a uniform disc
// (frame-measured on noir sg.MP4: 6-band study, all bands "denser-center"). A pellet lands / cores
// iff it falls within the boss body / core radius ⇒ the Rayleigh CDF. ONE σ drives BOTH SG landing
// and per-weapon core-hit (same cone at boss-body vs core radius), unifying Workstreams A/B/C.
export const K_SIGMA = 2.53;      // the visible spread disc (=circleDpx) is the ~2.5σ envelope
export const CORE_AUTOAIM = 0.55; // core-ONLY auto-aim loss (reticle never nails the ~1px true center)

// P(a pellet lands within radius R of the aim point) for an isotropic 2D Gaussian, σ.
export function rayleighWithin(R: number, sigma: number): number {
  if (sigma <= 0) return R > 0 ? 1 : 0;
  return 1 - Math.exp(-(R * R) / (2 * sigma * sigma));
}

// Pellet-spread σ (px) for a weapon at a given hit rate: half the (HR-shrunk) accuracy circle,
// divided by K_SIGMA. hr=0 gives AR 9.6 / SMG 14.1 / SG 32.0 px.
export function pelletSigma(
  scale: number,
  hr: number,
  slope: number,
  floorFrac: number,
): number {
  return circleDpxAtHr(scale, hr, slope, floorFrac) / 2 / K_SIGMA;
}

// Boss-body radius per band (px) from the measured hand-outlined area fraction: R_boss =
// R_disc·sqrt(hitFrac), where R_disc = circleDpx(250)/2 = 81 (noir reference). Reuses the measured
// silhouette; the Gaussian just re-weights the overlap. profileScale scales the boss size per boss.
export function bossBodyRadius(hitFrac: number, profileScale = 1): number {
  const RDISC = circleDpx(250) / 2;
  return RDISC * Math.sqrt(Math.max(0, hitFrac)) * profileScale;
}

// SG pellet-landing fraction: Gaussian cone (σ) overlapping the boss body (R_boss).
export function pelletLandFrac(hitFrac: number, sigma: number, profileScale = 1): number {
  return rayleighWithin(bossBodyRadius(hitFrac, profileScale), sigma);
}

// Core-hit fraction from the SAME cone at the core radius, with the core-only auto-aim loss.
export function pelletCoreFrac(coreDpxBand: number, sigma: number): number {
  return CORE_AUTOAIM * rayleighWithin(coreDpxBand / 2, sigma);
}

// ── δ-offset ("Rician") cone — the CONE_DELTA enactment model (owner-gated) ───────────────────────
// docs/handoffs/2026-07-19-core-geometry-implementation-plan.md §1 (basis:
// 2026-07-19-geometry-campaign-findings.md). REPLACES the two confirmed bugs of the live path — the
// flat `CORE_AUTOAIM=0.55` cap (structurally wrong: over-credits low-HR far, under-credits high-HR
// near) and the fractional reticle floor — with ONE mechanism: shots land on an isotropic Gaussian
// cone (σ from the accuracy circle at K_SIGMA) whose CENTER sits δ px off the true core (the auto-aim
// never nails the ~1px center); a shot cores iff it lands within the band core radius ⇒ the Rician
// CDF. δ shrinks with Hit Rate (auto-aim tightens onto the core), which is the work the flat cap
// crudely approximated. The measured campaign (blanc far spawn re-count 0.111[0.073,0.165] vs δ+σ
// prediction 0.103, δ-only 0.232 and centered 0.253 EXCLUDED) selects this family; the drawn reticle
// is decorative and anchors nothing here.
//
// FROZEN 2026-07-19 (owner-locked) — parameter-freeze refit + Fable pre-registration
// (docs/handoffs/2026-07-19-cone-param-freeze-prereg.md; reproducible in scripts/cone-refit.ts).
// δ0 fit by binomial MLE on the method-tagged cell set: AR spawn-confirmed (scarlet COUNT-1 near .25 /
// far .08; blanc far .111; Label HR23), SMG on the CLEAN chisato near cells (.294 HR0 / .365 HR22 —
// biased-high quency/LM near cells deliberately NOT used to set the offset), SG on dorothy HR0 + noir
// ▲60/▲98. K_SIGMA (2.53) held; CIRCLE_PX_K and the datamined per-weapon scale are measured constants,
// never refit (hard-constraint #3). σ-law (H, s, S_FLOOR): H and s pinned so the cone saturates near-core
// by the owner-attested jill ▲80 / noir ▲98 cells; S_FLOOR only bites at HR>~90 (saturation mechanism).
// ⚑ KNOWN, BOUNDED: the shared σ (fixed by the wide 110px SMG circle) over-credits SMG far/mid core
//   (the datamined circle width is not a free param) — same direction as the live AR-far over-credit,
//   small damage weight; watched by the board-A/B stop-condition, re-reviewable later.
// ⚑ NOT SUPPORTED: Hit Rate > 98 (owner-accepted; no board comp reaches it — σ-floor extrapolation only).
// σ-shrink is PER-WEAPON (owner 2026-07-19, board-driven): a single shared shrink could not both
//   saturate SG ▲98 core AND avoid over-crediting SMG mid-HR (quency ▲61) — the board A/B on the
//   shared-s freeze read quency +0.171 HOT. Decoupled: SG s pinned to saturate ▲98 (≈1.0; consistent
//   with the measured dorothy-serendipity ▲98.18 aimed-single-bullet coreRate 0.9 as the ceiling and
//   noir's ~1.0 spray attestation); AR s pinned to saturate jill ▲80; SMG s LOW (no SMG unit reaches
//   high HR, so SMG needs no saturation shrink) → keeps quency ▲61 at ~0.56 (≈ the biased-high measured
//   0.583) and chisato ▲22 near-exact. Low-HR cells are σ-shrink-invariant, so the clean chisato/
//   scarlet base cells are untouched. S_FLOOR shared (bites only at HR>~90).
export const CONE_DELTA0: Record<string, number> = { AR: 18, SMG: 16, SG: 30 }; // px @2622×1206, monotone in cone size
export const CONE_DELTA_H = 120;        // Hit Rate at which the centering offset δ reaches 0
export const CONE_SIGMA_SHRINK: Record<string, number> = { AR: 0.009, SMG: 0.004, SG: 0.009 }; // σ shrink per HR point, per weapon
export const CONE_SIGMA_FLOOR = 0.10;   // σ floor as a fraction of σ(0) (bites only at HR>~90)

// Pellet-spread σ (px) under the δ-cone model: half the accuracy circle / K_SIGMA, with a mild
// Hit-Rate σ-shrink (floored). Matches implementation-plan §2's sigma_w(hr). CIRCLE_PX_C is 0, so
// this equals circleDpx(scale)/2/K_SIGMA·shrink — written from CIRCLE_PX_K directly per the plan.
export function coneSigma(scale: number, hr: number, shrink: number): number {
  const s0 = (CIRCLE_PX_K * scale) / 2 / K_SIGMA;
  return s0 * Math.max(CONE_SIGMA_FLOOR, 1 - shrink * Math.max(0, hr));
}

// Per-weapon centering offset δ (px): DELTA0[weapon] shrinking linearly to 0 at Hit Rate H.
// Unknown weapon (MG/SR/RL) → 0 (they have no accuracy-circle model and never route here).
export function coneDelta(weapon: string, hr: number): number {
  const d0 = CONE_DELTA0[weapon];
  if (d0 === undefined) return 0;
  return d0 * Math.max(0, 1 - Math.max(0, hr) / CONE_DELTA_H);
}

// Modified Bessel function I₀(x) — Abramowitz & Stegun 9.8.1/9.8.2 rational approximations
// (|error| < 2e-7). Needed for the off-center Rician CDF integrand below.
export function besselI0(x: number): number {
  const ax = Math.abs(x);
  if (ax < 3.75) {
    const t = x / 3.75;
    const t2 = t * t;
    return (
      1 +
      t2 *
        (3.5156229 +
          t2 * (3.0899424 + t2 * (1.2067492 + t2 * (0.2659732 + t2 * (0.0360768 + t2 * 0.0045813)))))
    );
  }
  const t = 3.75 / ax;
  return (
    (Math.exp(ax) / Math.sqrt(ax)) *
    (0.39894228 +
      t *
        (0.01328592 +
          t *
            (0.00225319 +
              t *
                (-0.00157565 +
                  t *
                    (0.00916281 +
                      t *
                        (-0.02057706 +
                          t * (0.02635537 + t * (-0.01647633 + t * 0.00392377))))))))
  );
}

// P(‖N((δ,0), σ²·I)‖ ≤ R) — the probability a shot whose landing point is an isotropic 2D Gaussian
// of spread σ CENTERED δ px off the core lands within the core radius R (the Rician CDF). Derived in
// polar coords about the disc centre: P = ∫₀ᴿ (ρ/σ²)·exp(−(ρ²+δ²)/2σ²)·I₀(ρδ/σ²) dρ (the θ-integral
// gives 2π·I₀). Deterministic Simpson quadrature, no per-tick RNG. δ=0 reduces EXACTLY to
// rayleighWithin (special-cased so the reduction is analytic, not quadrature-approximate).
export function offsetCoreProb(R: number, sigma: number, delta: number): number {
  if (sigma <= 0) return R > 0 ? 1 : 0;
  if (R <= 0) return 0;
  if (delta === 0) return rayleighWithin(R, sigma); // exact centered reduction
  const s2 = sigma * sigma;
  const d2 = delta * delta;
  const N = 64; // even ⇒ Simpson
  const h = R / N;
  const f = (rho: number): number =>
    (rho / s2) * Math.exp(-(rho * rho + d2) / (2 * s2)) * besselI0((rho * delta) / s2);
  let sum = f(0) + f(R);
  for (let i = 1; i < N; i++) sum += (i % 2 ? 4 : 2) * f(i * h);
  return Math.min(1, (h / 3) * sum);
}
