import { useMemo, useState } from 'react';
import charactersJson from '../../../data/characters.json';
import archetypeTagsJson from '../../../data/archetype-tags.json';
import type { DataFile } from '../../../src/types';
import { useIconThumbs } from '../useIconThumbs';
import { usePortraitThumbs } from '../usePortraitThumbs';

const data = charactersJson as unknown as DataFile;

// Kit-role archetype tags (what a unit's kit DOES — buffer, reload buffer,
// distributed damage, …). Generated by scripts/build-archetype-tags.ts; see
// docs/data/archetype-tags.md. The `vocabulary` block carries the player-facing
// label + blurb so the UI never hardcodes them.
type ArchetypeTagsFile = {
  vocabulary: Record<string, { label: string; blurb: string; group: string }>;
  tags: Record<string, string[]>;
};
const archetypeData = archetypeTagsJson as unknown as ArchetypeTagsFile;

// Pills are bucketed into groups (Stat Buffs / Damage Buffs / Ally Filters /
// Burst Support / Role) for the filter panel. Group order = first appearance in
// the vocabulary and pill order within a group = vocabulary insertion order; both
// mirror the TAG_DEFS order in the build script, so the panel reads top-to-bottom
// in the same order the rules are defined there.
type ArchetypeOption = { id: string; label: string; blurb: string };
const ARCHETYPE_GROUPS: { group: string; options: ArchetypeOption[] }[] =
  (() => {
    const byGroup = new Map<string, ArchetypeOption[]>();
    for (const [id, v] of Object.entries(archetypeData.vocabulary)) {
      if (!byGroup.has(v.group)) byGroup.set(v.group, []);
      byGroup.get(v.group)!.push({ id, label: v.label, blurb: v.blurb });
    }
    return [...byGroup.entries()].map(([group, options]) => ({
      group,
      options,
    }));
  })();

// Icon-only filter row: a set of square icon buttons. Each button toggles on/off
// (multi-select). When no buttons in a row are selected, the filter is inactive
// (all values pass). When one or more are selected, only characters matching at
// least one selected value pass.
type FilterRowProps = {
  label: string;
  options: {
    id: string;
    icon: string;
    match?: (value: string) => boolean;
    imgStyle?: React.CSSProperties;
  }[];
  selected: Set<string>;
  onToggle: (id: string) => void;
  thumbs: Record<string, string>;
};

function FilterRow({
  label,
  options,
  selected,
  onToggle,
  thumbs,
}: FilterRowProps) {
  return (
    <div className='teambuilder-filter-row'>
      <span className='teambuilder-filter-label'>{label}</span>
      <div className='teambuilder-filter-icons'>
        {options.map((opt) => {
          const active = selected.has(opt.id);
          const src = `/nikke-icons/${opt.icon}`;
          // Tag icons that should keep their original colors when selected
          // (skip the brightness(0) filter). Weapon and burst icons are
          // monochrome but need to stay visible on the accent background.
          const isColored =
            opt.icon.startsWith('code_') ||
            opt.icon.startsWith('class_') ||
            opt.icon.startsWith('man_') ||
            opt.icon.startsWith('weapon_') ||
            opt.icon.startsWith('burst_');
          return (
            <button
              key={opt.id}
              className={'teambuilder-icon-btn' + (active ? ' on' : '')}
              onClick={() => onToggle(opt.id)}
              title={opt.id}
              aria-pressed={active}
            >
              <img
                src={src.endsWith('.svg') ? src : (thumbs[src] ?? src)}
                alt={opt.id}
                draggable={false}
                data-colored={isColored ? '' : undefined}
                style={opt.imgStyle}
              />
            </button>
          );
        })}
      </div>
    </div>
  );
}

// Filter option definitions — each option maps to an icon file and a match
// function. For manufacturers, the base icon matches both the base name and the
// "Overspec" variant (e.g. Elysion matches "Elysion" and "Elysion Overspec").
const WEAPON_OPTIONS = [
  { id: 'AR', icon: 'weapon_ar.png' },
  { id: 'SMG', icon: 'weapon_smg.png' },
  { id: 'SG', icon: 'weapon_sg.png' },
  { id: 'MG', icon: 'weapon_mg.png' },
  { id: 'SR', icon: 'weapon_sr.png' },
  { id: 'RL', icon: 'weapon_rl.png' },
];

const BURST_OPTIONS = [
  { id: 'I', icon: 'burst_1.svg', imgStyle: { padding: 8 } },
  { id: 'II', icon: 'burst_2.svg', imgStyle: { padding: 8 } },
  { id: 'III', icon: 'burst_3.svg', imgStyle: { padding: 8 } },
];
// Λ burst characters are included in every burst filter selection (no dedicated
// Λ icon exists, and they're rare enough that a separate filter isn't needed).

const ICON_PAD: React.CSSProperties = { padding: 4 };

const CLASS_OPTIONS = [
  { id: 'Attacker', icon: 'class_attacker.webp', imgStyle: ICON_PAD },
  { id: 'Defender', icon: 'class_defender.webp', imgStyle: ICON_PAD },
  { id: 'Supporter', icon: 'class_support.webp', imgStyle: ICON_PAD },
];

const ELEMENT_OPTIONS = [
  { id: 'Fire', icon: 'code_fire.svg', imgStyle: ICON_PAD },
  { id: 'Water', icon: 'code_water.svg', imgStyle: ICON_PAD },
  { id: 'Wind', icon: 'code_wind.svg', imgStyle: ICON_PAD },
  { id: 'Electric', icon: 'code_electric.svg', imgStyle: ICON_PAD },
  { id: 'Iron', icon: 'code_iron.svg', imgStyle: ICON_PAD },
];

// Base manufacturer names — selecting one also matches its Overspec variant.
// Ordered: Elysion, Missilis, Tetra, Pilgrim, Abnormal
const MANUFACTURER_OPTIONS = [
  {
    id: 'Elysion',
    icon: 'man_elysion.webp',
    imgStyle: ICON_PAD,
    match: (v: string) => v === 'Elysion' || v === 'Elysion Overspec',
  },
  {
    id: 'Missilis',
    icon: 'man_missilis.webp',
    imgStyle: ICON_PAD,
    match: (v: string) => v === 'Missilis' || v === 'Missilis Overspec',
  },
  {
    id: 'Tetra',
    icon: 'man_tetra.webp',
    imgStyle: ICON_PAD,
    match: (v: string) => v === 'Tetra' || v === 'Tetra Overspec',
  },
  {
    id: 'Pilgrim',
    icon: 'man_pilgrim.webp',
    imgStyle: ICON_PAD,
    match: (v: string) => v === 'Pilgrim',
  },
  {
    id: 'Abnormal',
    icon: 'man_abnormal.webp',
    imgStyle: ICON_PAD,
    match: (v: string) => v === 'Abnormal',
  },
];

// All filter icon URLs — collected once so useIconThumbs can pre-downscale
// them. SVGs are excluded: the browser rasterizes vectors natively at device
// resolution (FilterRow uses the raw URL for them), so pre-downscaling would
// only soften them.
const FILTER_ICON_URLS = [
  ...WEAPON_OPTIONS,
  ...BURST_OPTIONS,
  ...CLASS_OPTIONS,
  ...ELEMENT_OPTIONS,
  ...MANUFACTURER_OPTIONS,
]
  .map((opt) => `/nikke-icons/${opt.icon}`)
  .filter((url) => !url.endsWith('.svg'));

function emptySet(): Set<string> {
  return new Set();
}

// The filterable full-roster grid, shared by the Browse Nikkes modals (Team
// Sim / Roster Sim) and the Team Builder page. Clicking a card calls onToggle:
// the caller owns the team and decides what add/remove mean. Units in `exclude`
// are already placed and disappear from the list entirely. Units the sim
// doesn't model yet ("Not In Sim") only appear on the Team Builder page
// (allowUnsupported), which lets them be picked and warns at copy time; the
// Browse/Include/Exclude modals hide them from the grid entirely. Class names
// keep their `teambuilder-` prefix from the page this was extracted from.
export function CharacterGrid({
  exclude,
  onToggle,
  allowUnsupported = false,
  restrict,
}: {
  exclude: Set<string>;
  onToggle: (slug: string) => void;
  allowUnsupported?: boolean;
  // when set, only these slugs are browsable (the generator modals restrict the
  // pool to the units the generator can actually field); omit = every unit
  restrict?: Set<string>;
}) {
  const [search, setSearch] = useState('');
  const [weaponFilter, setWeaponFilter] = useState<Set<string>>(emptySet);
  const [burstFilter, setBurstFilter] = useState<Set<string>>(emptySet);
  const [classFilter, setClassFilter] = useState<Set<string>>(emptySet);
  const [elementFilter, setElementFilter] = useState<Set<string>>(emptySet);
  const [manufacturerFilter, setManufacturerFilter] =
    useState<Set<string>>(emptySet);
  const [archetypeFilter, setArchetypeFilter] = useState<Set<string>>(emptySet);

  // Pre-downscale filter icons (40px CSS) and card mini-icons (18px CSS) via
  // stepped-halving so the browser never aliases them at render time.
  const filterThumbs = useIconThumbs(FILTER_ICON_URLS, 40);
  const miniIconUrls = useMemo(() => {
    const urls = new Set<string>();
    Object.values(data.characters).forEach((c) => {
      // Raster sources only — SVGs (element/burst) are rendered natively by
      // the browser at device resolution; canvas-rasterizing them here would
      // only blur them.
      urls.add(`/nikke-icons/weapon_${c.weapon.toLowerCase()}.png`);
      // Class icon: 'Supporter' → 'class_support.webp' (file named without 'er')
      const classFile =
        c.class === 'Supporter' ? 'support' : c.class.toLowerCase();
      urls.add(`/nikke-icons/class_${classFile}.webp`);
    });
    return Array.from(urls);
  }, []);
  const miniThumbs = useIconThumbs(miniIconUrls, 18);

  const toggle = (current: Set<string>, setter: (s: Set<string>) => void) => {
    return (id: string) => {
      const next = new Set(current);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      setter(next);
    };
  };

  const characters = useMemo(() => {
    const all = Object.values(data.characters).filter(
      (c) =>
        (!restrict || restrict.has(c.slug)) &&
        // "Not In Sim" units only appear on the Team Builder page; hide them
        // from the Browse/Include/Exclude modals entirely
        (allowUnsupported || c.simSupported),
    );
    const q = search.toLowerCase();
    return all.filter((c) => {
      // Already placed — removed from the list entirely
      if (exclude.has(c.slug)) return false;
      // Text search — slug, name, or approved community nickname
      if (q) {
        const textMatch =
          c.slug.includes(q) ||
          c.name.toLowerCase().includes(q) ||
          (c.nicknames ?? []).some((n) => n.includes(q));
        if (!textMatch) return false;
      }
      // Weapon filter
      if (weaponFilter.size > 0 && !weaponFilter.has(c.weapon)) return false;
      // Burst filter — Λ burst characters are always included (no dedicated filter)
      if (burstFilter.size > 0 && c.burst !== 'Λ' && !burstFilter.has(c.burst))
        return false;
      // Class filter
      if (classFilter.size > 0 && !classFilter.has(c.class)) return false;
      // Element filter
      if (elementFilter.size > 0 && !elementFilter.has(c.element)) return false;
      // Manufacturer filter — use the match function if present, else exact match
      if (manufacturerFilter.size > 0) {
        const matched = MANUFACTURER_OPTIONS.some(
          (opt) =>
            manufacturerFilter.has(opt.id) &&
            (opt.match
              ? opt.match(c.manufacturer ?? '')
              : c.manufacturer === opt.id),
        );
        if (!matched) return false;
      }
      // Archetype filter — OR within the row (a unit passes if it carries ANY
      // selected tag), AND with the other rows. Units with no tags only pass
      // while the row is inactive.
      if (archetypeFilter.size > 0) {
        const unitTags = archetypeData.tags[c.slug] ?? [];
        if (!unitTags.some((t) => archetypeFilter.has(t))) return false;
      }
      return true;
    });
  }, [
    exclude,
    restrict,
    allowUnsupported,
    search,
    weaponFilter,
    burstFilter,
    classFilter,
    elementFilter,
    manufacturerFilter,
    archetypeFilter,
  ]);

  // Pre-downscale character portraits (120px CSS card width) using the same
  // stepped-halving pipeline as the Team Sim page. Computed from all characters
  // (not filtered) so the hook call order stays stable across filter changes.
  const allPortraitUrls = useMemo(
    () =>
      Object.values(data.characters)
        .map((c) => c.imageUrl)
        .filter(Boolean) as string[],
    [],
  );
  const portraitThumbs = usePortraitThumbs(allPortraitUrls, 120);

  const total = Object.values(data.characters).filter(
    (c) =>
      (!restrict || restrict.has(c.slug)) &&
      (allowUnsupported || c.simSupported),
  ).length;
  const showing = characters.length;
  const anyActive =
    search !== '' ||
    weaponFilter.size > 0 ||
    burstFilter.size > 0 ||
    classFilter.size > 0 ||
    elementFilter.size > 0 ||
    manufacturerFilter.size > 0 ||
    archetypeFilter.size > 0;

  return (
    <div className='teambuilder-picker'>
      <details className='teambuilder-filters-details' open>
        <summary>Filters</summary>
        <div className='teambuilder-filters'>
          {/* Left — the stat-axis icon rows */}
          <div className='teambuilder-filters-stat'>
            <FilterRow
              label='Weapon'
              options={WEAPON_OPTIONS}
              selected={weaponFilter}
              onToggle={toggle(weaponFilter, setWeaponFilter)}
              thumbs={filterThumbs}
            />
            <FilterRow
              label='Burst'
              options={BURST_OPTIONS}
              selected={burstFilter}
              onToggle={toggle(burstFilter, setBurstFilter)}
              thumbs={filterThumbs}
            />
            <FilterRow
              label='Class'
              options={CLASS_OPTIONS}
              selected={classFilter}
              onToggle={toggle(classFilter, setClassFilter)}
              thumbs={filterThumbs}
            />
            <FilterRow
              label='Element'
              options={ELEMENT_OPTIONS}
              selected={elementFilter}
              onToggle={toggle(elementFilter, setElementFilter)}
              thumbs={filterThumbs}
            />
            <FilterRow
              label='Manufacturer'
              options={MANUFACTURER_OPTIONS}
              selected={manufacturerFilter}
              onToggle={toggle(manufacturerFilter, setManufacturerFilter)}
              thumbs={filterThumbs}
            />
          </div>

          {/* Right — kit-role archetype pills (fill the space beside the icon
            rows), bucketed into groups. Labels + blurbs + group names all come
            from the generated vocabulary; nothing is hardcoded here. */}
          <div className='teambuilder-archetypes'>
            {ARCHETYPE_GROUPS.map(({ group, options }) => (
              <div className='teambuilder-archetype-group' key={group}>
                <span className='teambuilder-archetype-group-label'>
                  {group}
                </span>
                <div className='teambuilder-archetype-pills'>
                  {options.map((opt) => {
                    const active = archetypeFilter.has(opt.id);
                    return (
                      <button
                        key={opt.id}
                        type='button'
                        className={'teambuilder-pill' + (active ? ' on' : '')}
                        onClick={() =>
                          toggle(archetypeFilter, setArchetypeFilter)(opt.id)
                        }
                        title={opt.blurb}
                        aria-pressed={active}
                      >
                        {opt.label}
                      </button>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>
      </details>

      <div className='teambuilder-search'>
        <input
          type='text'
          placeholder='Search by name or nickname…'
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        {search && (
          <button
            className='teambuilder-search-clear'
            onClick={() => setSearch('')}
            aria-label='Clear search'
          >
            ×
          </button>
        )}
      </div>

      {anyActive && (
        <div className='teambuilder-count muted'>
          Showing {showing} of {total} NIKKEs
          <button
            className='teambuilder-clear'
            onClick={() => {
              setSearch('');
              setWeaponFilter(emptySet());
              setBurstFilter(emptySet());
              setClassFilter(emptySet());
              setElementFilter(emptySet());
              setManufacturerFilter(emptySet());
              setArchetypeFilter(emptySet());
            }}
          >
            Clear all
          </button>
        </div>
      )}

      <div className='teambuilder-grid'>
        {characters.map((c) => {
          const weaponSrc = `/nikke-icons/weapon_${c.weapon.toLowerCase()}.png`;
          const elementSrc = `/nikke-icons/code_${c.element.toLowerCase()}.svg`;
          const burstSrc = `/nikke-icons/burst_${c.burst === 'I' ? '1' : c.burst === 'II' ? '2' : '3'}.svg`;
          // Class icon: 'Supporter' → 'class_support.webp' (file named without 'er')
          const classFile =
            c.class === 'Supporter' ? 'support' : c.class.toLowerCase();
          const classSrc = `/nikke-icons/class_${classFile}.webp`;
          return (
            <button
              key={c.slug}
              type='button'
              className={`teambuilder-card${c.simSupported ? '' : ' unsupported'}`}
              onClick={() => onToggle(c.slug)}
              title={
                c.simSupported
                  ? `${c.name} — click to add to team`
                  : `${c.name} — not in the sim yet (can be placed, but not simmed)`
              }
            >
              <div className='teambuilder-portrait'>
                {c.imageUrl ? (
                  <img
                    src={portraitThumbs[c.imageUrl] ?? c.imageUrl}
                    alt={c.name}
                    loading='lazy'
                  />
                ) : (
                  <span className='teambuilder-portrait-empty'>?</span>
                )}
                {!c.simSupported && (
                  <span className='teambuilder-unsupported-badge'>
                    Not In Sim
                  </span>
                )}
              </div>
              <div className='teambuilder-card-info'>
                <span className='teambuilder-card-name'>{c.name}</span>
                <div className='teambuilder-card-icons'>
                  <img
                    src={miniThumbs[weaponSrc] ?? weaponSrc}
                    alt={c.weapon}
                    title={c.weapon}
                    className='teambuilder-mini-icon'
                  />
                  <img
                    src={elementSrc}
                    alt={c.element}
                    title={c.element}
                    className='teambuilder-mini-icon'
                  />
                  <img
                    src={burstSrc}
                    alt={`Burst ${c.burst}`}
                    title={`Burst ${c.burst}`}
                    className='teambuilder-mini-icon'
                  />
                  <img
                    src={miniThumbs[classSrc] ?? classSrc}
                    alt={c.class}
                    title={c.class}
                    className='teambuilder-mini-icon'
                  />
                </div>
              </div>
            </button>
          );
        })}
      </div>

      {characters.length === 0 && (
        <div className='teambuilder-empty muted'>
          No NIKKEs match the selected filters.
        </div>
      )}
    </div>
  );
}
